dojo/widgets

Gruntfile.js, package.json
**Type:** bug
- Fixes `widget-core` version in package.json
- Adds calls to `postcss:modules` and `postcss:variables`.
=> fix package.json add postcss tasks

Gruntfile.js, tests/intern-saucelabs.ts
**Type:** bug
Update the Gruntfile to properly configure `dist` and `dev` tasks. **Note:** depends on dojo/grunt-dojo2#88.
Resolves #9
=> Update Gruntfile for correct dist and dev support

package.json, src/dialog/Dialog.ts, src/dialog/example/index.ts, src/slidepane/SlidePane.ts, src/slidepane/example/index.ts, tests/unit/Dialog.ts, tests/unit/SlidePane.ts
Update `widget-core` to the latest alpha release and make slight adjustments required (properties are no longer passed to the constructor).
Also ensure that all types required to create declarations (`d.ts` files) are imported and referenced (so that `grunt dist` runs)
=> Upgrade widget core

package.json
Resolves https://github.com/dojo/meta/issues/152
=> Bump TS to version 2.2.1

README.md
Updated readme with icon and spacing conventions. Marked our deployment and install instructions as preliminary.
=> Update README.md for icon and relative unit decisions.

package.json
**Type:** bug
correct the package.json name
=> correct the package.json name

src/checkbox/example/index.html, src/common/tests/intern.ts, src/dialog/example/index.html, src/label/example/index.html, src/radio/example/index.html, src/slidepane/example/index.html, src/textarea/example/index.html, src/textinput/example/index.html
Add configuration required for intern and examples needed to support https://github.com/dojo/widget-core/pull/390#issuecomment-285087563
=> Add polyfill config for intern and examples

LICENSE
=> Updated LICENSE file

package.json, src/dialog/createDialogElement.ts, src/slidepane/createSlidePaneElement.ts
Updates `@dojo/core` to alpha.26 to avoid "unmet peer dependency" errors on install.
=> Update @dojo/core to alpha.26

README.md
=> Update README with more details for beta 1

package.json
=> Added npm 3 min version to package.json

package.json
**Type:** bug
All dojo2 deps should be peer dependencies over deps as that is the current standard.
=> Change deps to peer deps

src/combobox/ComboBox.ts
Changes required by the next release of `widget-core` due to the `breaking-change` pull requests:
https://github.com/dojo/widget-core/pull/425
Requires release of `widget-core`.
=> Changes for upcoming `widget-core` release

src/slidepane/SlidePane.ts
=> Remove stop propogation and prevent default on touchStart

src/combobox/ComboBox.ts, src/combobox/tests/unit/ComboBox.ts, src/common/tests/unit/all.ts, src/common/tests/unit/util.ts, src/common/util.ts, src/select/Select.ts, src/tabpane/TabButton.ts, src/tabpane/tests/unit/TabButton.ts
Moves key codes to `common/util`, and updates all widgets that use them (Select, ComboBox, and TabPane).
=> Util for key codes

.travis.yml, src/common/tests/intern.ts
Migrates to BrowserStack for CI testing.
=> Change to BrowserStack for CI testing

src/combobox/tests/unit/ComboBox.ts
=> Change test to fail when passing through custom Widgets

src/button/styles/button.m.css, src/combobox/styles/comboBox.m.css, src/dialog/styles/dialog.m.css, src/select/styles/select.m.css, src/slider/styles/slider.m.css, src/tabpane/styles/tabPane.m.css, src/themes/dojo/checkbox.m.css, src/themes/dojo/dialog.m.css, src/themes/dojo/radio.m.css, src/themes/dojo/slider.m.css
**Type:** bug
Some focus styles had been removed without replacement in recent theming shuffles.
=> Fix focus styles

src/common/example/index.html, src/common/example/index.ts
=> Add widget drop down to example page

src/common/tests/functional/all.ts, src/tabpane/tests/functional/TabPane.ts
=> Add `TabPane` functional tests.

src/common/tests/functional/all.ts, src/radio/example/index.ts, src/radio/tests/functional/Radio.ts
=> Add `Radio` button functional tests

src/checkbox/example/index.ts, src/checkbox/tests/functional/Checkbox.ts, src/common/tests/functional/all.ts
=> Add `Checkbox` functional tests.

src/button/example/index.ts, src/button/tests/functional/Button.ts, src/common/tests/functional/all.ts
=> Add `Button` functional tests.

src/common/tests/functional/all.ts, src/textinput/example/index.ts, src/textinput/tests/functional/TextInput.ts
=> Add `TextInput` functional tests

src/tabpane/TabPane.ts
This PR gives TabPane some type love for its main internal `_tabs` property.
Resolves #208
=> Type internal TabPane properties better

src/tabpane/TabPane.ts
=> Use Tab import rather than re-defining

src/checkbox/Checkbox.ts, src/checkbox/README.md, src/checkbox/example/index.ts, src/radio/README.md, src/radio/example/index.ts
Resolves #181 and #187, adds readmes for the checkbox and radio widgets. Also includes minor modifications to typings and Checkbox toggle a11y to make the READMEs accurate.
=> Checkbox and Radio READMEs

src/textinput/README.md, src/textinput/example/index.ts
Resolves #192, adds TextInput readme, and also fixes TextInput event typings in the example.
=> TextInput Readme

src/textarea/README.md, src/textarea/example/index.ts
Resolves #191, adds Textarea readme; also fixes event typings in example page.
=> Textarea Readme

src/label/README.md
Resolves #184, adds Label readme. The readme does not contain information on passing classes at the moment, since it is still under discussion. I think that content should be added with #167, when a final decision is reached.
=> Label README

src/slidepane/README.md
=> SlidePane README

src/combobox/README.md, src/dialog/README.md
=> ComboBox README

src/common/styles/icons.m.css, src/select/Select.ts, src/select/styles/select.m.css, src/select/styles/select.m.css.d.ts, src/select/tests/unit/Select.ts, src/themes/dojo/select.m.css, src/themes/dojo/variables.css
=> Select theme

src/select/Select.ts, tsconfig.json
This PR are the updates required to support updates to `@dojo/shim`.
Refs: dojo/shim#101
=> Update for @dojo/shim

src/button/tests/unit/Button.ts, src/common/tests/unit/main.ts, src/select/Select.ts, src/select/SelectOption.ts, src/select/tests/unit/Select.ts, src/select/tests/unit/SelectOption.ts, src/slidepane/tests/unit/SlidePane.ts, src/splitpane/tests/unit/SplitPane.ts
Resolves #288
- Updates Select unit tests
- Moves `has('touch')` check to `common/tests/unit/main`
=> Select unit tests updated to use test-extras

src/radio/tests/unit/Radio.ts
=> Radio unit tests updated to use test-extras

src/tabcontroller/TabController.ts, src/tabcontroller/tests/unit/Tab.ts, src/tabcontroller/tests/unit/TabButton.ts, src/tabcontroller/tests/unit/TabController.ts
=> TabController unit tests updated to use test-extras

src/label/Label.ts, src/label/styles/label.m.css, src/label/styles/label.m.css.d.ts, src/label/tests/unit/Label.ts
=> Added class to the label span

package.json
Updated the homepage URL in package.json to point to https://dojo.io.
Refs: dojo/meta#166
=> Update Dojo URL in package.json

src/common/tests/run.html
**Type:** bug
Should fix local tests
=> Fix intern config path

intern.json
**Type:** bug
With this setting, mouse positioned events and focused events are failing for the Dialog functional tests.
=> Remove fixSessionCapabilities

src/themes/dojo/checkbox.m.css, src/themes/dojo/radio.m.css, src/themes/dojo/slidePane.m.css, src/themes/dojo/timePicker.m.css, src/themes/dojo/variables.css
**Type:** bug
We still had some old variables hanging around the dojo theme and cluttering the `variables.css` file. This PR removes them once and for all 🔥
=> Update old theme variables

.travis.yml, intern.json, src/accordionpane/tests/functional/AccordionPane.ts, src/slidepane/example/index.ts, src/slidepane/tests/functional/SlidePane.ts, src/textinput/example/index.ts, src/textinput/tests/functional/TextInput.ts
**Type:** bug
* Run Firefox on Windows 10 to always get latest version
* Change AccordionPane test to click on heading (Edge and Safari drivers have broken click)
* Change TextInput example to use onInput (Edge and Safari drivers don't fire onChange correctly)
* Change TextInput test to compare active element instead of CSS classes
=> Fix broken functional tests

src/themes/dojo/checkbox.m.css, src/themes/dojo/radio.m.css, src/themes/dojo/select.m.css
**Type:** bug
Resolves #351 and #352
=> Radio, Checkbox, and Select background colors

README.md, src/combobox/styles/comboBox.m.css, src/common/styles/variables.css, src/dialog/styles/dialog.m.css, src/select/styles/select.m.css, src/slidepane/styles/slidePane.m.css, src/slider/styles/slider.m.css, src/tabcontroller/styles/tabController.m.css, src/themes/dojo/comboBox.m.css, src/themes/dojo/dialog.m.css, src/themes/dojo/select.m.css, src/themes/dojo/slidePane.m.css, src/themes/dojo/slider.m.css, src/themes/dojo/titlePane.m.css, src/themes/dojo/variables.css, src/titlepane/styles/titlePane.m.css
Resolves #335.
Some styles were modified to reduce the use of tabIndex, particularly in TabController. Z-index styles were also removed from fixed classes.
=> Z-index organization

src/common/tests/functional/all.ts, src/label/Label.ts, src/label/example/index.ts, src/label/tests/functional/Label.ts, src/textinput/tests/functional/TextInput.ts
Adds basic functional tests for `Label` based on lzhoucs's PR https://github.com/dojo/widgets/pull/171 with rebasing and updates.
Resolves #153
=> Label functional tests

package.json, src/themes/dojo/select.m.css
**Type:** bug 
Fixes a styling inconsistency in Select.
Fixes missing icons / drop down styles
#295 #299
=> Fix select styling inconsistency and fix icon issues

src/common/tests/functional/all.ts, src/dialog/example/index.ts, src/dialog/tests/functional/Dialog.ts
Adds basic functional tests for `Dialog` based on mwistrand's PR https://github.com/dojo/widgets/pull/134 with rebasing and updates.
Resolves #152
=> Dialog functional tests

src/common/tests/functional/all.ts, src/splitpane/example/index.ts, src/splitpane/tests/functional/SplitPane.ts
Adds identifiers to SplitPane examples with functional tests.
Resolves #212
=> Add SplitPane Functional Tests

intern.json, package.json, src/common/example/index.html, tsconfig.json
Using TS helpers from https://github.com/dojo/shim/pull/114, and using the grunt-dojo2 intern loader.
=> Importing ts helpers from shim, using intern loader from grunt-dojo2

package-lock.json, package.json, src/accordionpane/example/index.ts, src/button/example/index.ts, src/calendar/DatePicker.ts, src/calendar/example/index.ts, src/checkbox/example/index.ts, src/combobox/example/index.ts, src/dialog/example/index.ts, src/listbox/example/index.ts, src/radio/example/index.ts, src/select/example/index.ts, src/slidepane/example/index.ts, src/slider/example/index.ts, src/splitpane/example/index.ts, src/tabcontroller/example/index.ts, src/textarea/example/index.ts, src/textinput/example/index.ts, src/themes/dojo/variables.css.d.ts, src/themes/dojo/widgets.css.d.ts, src/timepicker/example/index.ts, src/titlepane/example/index.ts, src/tooltip/example/index.ts, tsconfig.json
**Type:** enhancement
Relates to dojo/meta#210
=> Upgrade to TypeScript 2.6.1, turn on strict, and bump minor version

src/common/example/example.css, src/common/example/index.ts, src/common/tests/unit/all.ts, src/progress/Progress.ts, src/progress/README.md, src/progress/createProgressElement.ts, src/progress/example/index.ts, src/progress/styles/progress.m.css, src/progress/styles/progress.m.css.d.ts, src/progress/tests/unit/Progress.ts, src/themes/dojo/progress.m.css, src/themes/dojo/progress.m.css.d.ts, src/themes/dojo/theme.ts, src/themes/dojo/widgets.css
Creates progress bar widget
Resolves #385
=> 385 - Progress Widget

src/select/Select.ts, src/select/example/index.ts, src/select/tests/unit/Select.ts
=> Select default for getOptionSelected

README.md
=> Added widgets and widget-showcase link to readme

package.json
Removes a dep
Refs https://github.com/dojo/meta/issues/223
=> Remove the dojo interfaces dep

package-lock.json, package.json
**Type:** bug
Refs https://github.com/dojo/meta/issues/226
=> Move tslib from dev dep to dep

package-lock.json, src/common/example/example.css, src/label/example/index.ts, src/theme/checkbox/checkbox.m.css, src/theme/label/label.m.css, src/theme/radio/radio.m.css, src/theme/select/select.m.css, src/theme/textarea/textarea.m.css, src/theme/textinput/textinput.m.css, src/themes/dojo/label.m.css
**Type:** bug 
Adds required label styles to label css
Resolves #373
=> 373 - Add required label styles

src/toolbar/README.md
=> fix typo in toolbar readme

package-lock.json, package.json, src/calendar/tests/unit/CalendarCell.ts, src/combobox/ComboBox.ts, src/combobox/tests/unit/ComboBox.ts, src/dialog/Dialog.ts, src/listbox/Listbox.ts, src/listbox/tests/unit/Listbox.ts, src/select/Select.ts, src/select/tests/unit/Select.ts, src/slidepane/SlidePane.ts, src/slidepane/tests/unit/SlidePane.ts, src/splitpane/SplitPane.ts, src/textinput/TextInput.ts, src/titlepane/TitlePane.ts, src/titlepane/example/index.ts, src/titlepane/tests/unit/TitlePane.ts
Refactored usages of `onElementCreated` and `onElementUpdated`in widgets as the hooks are being removed from [`@dojo/widget-core/WidgetBase`](https://github.com/dojo/widget-core/pull/840).
=> Refactor usages of `onElementCreated` and `onElementUpdated`

src/tabcontroller/TabButton.ts, src/tabcontroller/tests/unit/TabButton.ts, src/theme/tabcontroller/tabController.m.css, src/theme/tabcontroller/tabController.m.css.d.ts, src/theme/timepicker/timePicker.m.css, src/theme/timepicker/timePicker.m.css.d.ts
Necessary className updates for theme style changes addressing #465
=> Update timepicker and tabpane classes

src/calendar/DatePicker.ts, src/calendar/tests/unit/DatePicker.ts, src/checkbox/index.ts, src/radio/index.ts, src/select/index.ts, src/select/tests/unit/Select.ts, src/text-area/index.ts, src/text-input/index.ts
**Type:** bug
Removes remaining event propagation.
=> Stop remaining event propagation

README.md, src/accordion-pane/README.md, src/button/README.md, src/calendar/README.md, src/checkbox/README.md, src/combobox/README.md, src/dialog/README.md, src/enhanced-text-input/README.md, src/global-event/README.md, src/label/README.md, src/progress/README.md, src/radio/README.md, src/slide-pane/README.md, src/slider/README.md, src/tab-controller/README.md, src/text-area/README.md, src/text-input/README.md, src/time-picker/README.md, src/title-pane/README.md, src/toolbar/README.md, src/tooltip/README.md
**Type:** bug
Updates paths and imports
Resolves #492
=> Update Readmes for new widget paths

package-lock.json, package.json
Updates to the latest dojo dependencies.
=> Update @dojo dependencies

src/checkbox/index.ts, src/split-pane/index.ts
**Type:** bug
Adds remaining string properties as custom element attributes
=> Custom element string attributes

intern.json
**Type:** bug
Pass chrome version as `2.36` (believe this sets chrome-driver version)
Resolves #518
=> update chrome driver version

src/button/index.ts, src/button/tests/unit/Button.ts, src/calendar/DatePicker.ts, src/calendar/index.ts, src/calendar/tests/unit/Calendar.ts, src/calendar/tests/unit/DatePicker.ts, src/combobox/index.ts, src/combobox/tests/unit/ComboBox.ts, src/dialog/index.ts, src/dialog/tests/unit/Dialog.ts, src/select/index.ts, src/select/tests/unit/Select.ts, src/slide-pane/index.ts, src/title-pane/index.ts, src/title-pane/tests/unit/TitlePane.ts, src/toolbar/index.ts, src/toolbar/tests/unit/Toolbar.ts
**Type:** bug
Ensure that `theme` is passed to `Icon` widget.
Resolves #522
=> Ensure Icon is themed correctly

src/progress/README.md
[skip ci]
**Type:** documentation
**Description:** Minor readme update
=> Update Progress readme to US English, fix typo

intern.json, package-lock.json, package.json, src/button/example/index.ts, src/calendar/example/index.ts, src/calendar/index.ts, src/combobox/example/index.ts, src/combobox/index.ts, src/dialog/index.ts, src/enhanced-text-input/example/index.ts, src/listbox/example/index.ts, src/radio/example/index.ts, src/select/example/index.ts, src/slide-pane/index.ts, src/slide-pane/tests/unit/SlidePane.ts, src/slider/example/index.ts, src/split-pane/index.ts, src/tab-controller/TabButton.ts, src/text-area/example/index.ts, src/text-input/example/index.ts, src/time-picker/example/index.ts, src/time-picker/index.ts, src/title-pane/index.ts, src/toolbar/index.ts
Start to prepare for compatibility with TS2.7 (not quite there as there is an outstanding issue with defaulting optional properties) and upgrade with dojo RC2 changes.
Requires release of i18n, widget-core, test-extras
=> TS2.7 forwards compatibility

src/split-pane/styles/split-pane.m.css
**Type:** bug
Addresses the first point of #536
=> Add larger split-pane drag target

package-lock.json, package.json
=> Pin node typings

src/combobox/index.ts, src/combobox/tests/unit/ComboBox.ts, src/theme/combobox.m.css
**Type:** bug
Necessary for theme PR to fix styles for IE11, and good change in general.
=> Better solution for hiding SR-only text

README.md, intern.json, src/accordion-pane/README.md, src/button/README.md, src/calendar/README.md, src/checkbox/README.md, src/combobox/README.md, src/dialog/README.md, src/enhanced-text-input/README.md, src/global-event/README.md, src/icon/README.md, src/label/README.md, src/listbox/README.md, src/progress/README.md, src/radio/README.md, src/select/README.md, src/slide-pane/README.md, src/slider/README.md, src/split-pane/README.md, src/tab-controller/README.md, src/text-area/README.md, src/text-input/README.md, src/time-picker/README.md, src/title-pane/README.md, src/toolbar/README.md, src/tooltip/README.md
**Type:** bug
Update references to `@dojo/widget-core` to `@dojo/framework/widget-core` and change "Dojo 2" to "Dojo".
=> README Updates

package-lock.json, src/common/tests/support/test-helpers.ts, src/grid/tests/unit/widgets/Cell.ts, src/grid/widgets/Cell.ts, src/grid/widgets/styles/Cell.m.css, src/grid/widgets/styles/Cell.m.css.d.ts
Addresses #586. Adds an edit button that is visible on focus, and handles focus between the input and button when switching into and out of edit mode.
This is primarily a quick fix, and ideally should be updated so that interactive grids use the ARIA grid spec for cell navigation and interaction.
=> Increase keyboard support for cell editing

package-lock.json, src/common/example/example.css, src/common/example/index.ts, src/grid/example/index.ts, src/grid/example/mockData.ts, src/grid/widgets/styles/Header.m.css
=> Add example page for grid

src/select/example/index.ts, src/select/index.ts, src/select/tests/unit/Select.ts
=> Select: support keyboard selecting by partially typing label

src/grid/README.md
**Type:** bug
Update grid readme to detail ResizeObserver requirement.
=> Add ResizeObserver requirement to README

README.md
=> fix import path in readme

src/grid/README.md, src/grid/example/index.ts, src/grid/interfaces.d.ts, src/grid/processes.ts, src/grid/tests/unit/processes.ts, src/grid/tests/unit/utils.ts, src/grid/tests/unit/widgets/Header.ts, src/grid/utils.ts, src/grid/widgets/Grid.ts, src/grid/widgets/Header.ts
Support filtering the grid across multiple columns.
Resolves #624
=> Multiple Column Filtering

src/slide-pane/example/index.ts, src/slide-pane/index.ts, src/slide-pane/styles/slide-pane.m.css, src/slide-pane/styles/slide-pane.m.css.d.ts, src/slide-pane/tests/unit/SlidePane.ts
* [ x ] There is a related issue
* [ x ] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
Not sure whether Unit or Functional tests are necessary for this PR, since I just changed the CSS.
Resolves #641
=> Added overflow-y: auto; to slide-pane

package-lock.json, package.json
Updates the remaining Dojo dependencies to `next` (alpha release of 5.0.0)
=> Update Dojo Dependencies

src/grid/README.md
Updates the grid readme to include more information for the properties, utils and themes.
=> Updates to the grid readme

README.md
**Type:** bug
Add `grid` to main readme.
=> Add grid to main readme

src/common/styles/variables.css
Removes color / color-mod usage
=> Calc underlay color to remove color function usage

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
**Type:** bug
- remove reference to Dojo 2
- point to CONTRIBUTING.md at dojo/framework
- replace gitter link with Discord
- point to STYLE.md at dojo/framework
=> update issue template with proper links

tsconfig.json
This is a simple update to the tsconfig.json to allow for TSX in modules to facilitate work for #713 and others.
=> Add support for TSX to TSConfig

package-lock.json, src/common/example/example.css, src/common/example/index.ts, src/common/tests/functional/all.ts, src/common/tests/unit/all.ts, src/outlined-button/README.md, src/outlined-button/example/index.ts, src/outlined-button/index.tsx, src/outlined-button/tests/functional/OutlinedButton.ts, src/outlined-button/tests/unit/OutlinedButton.tsx, src/theme/outlined-button.m.css, src/theme/outlined-button.m.css.d.ts
Adds an outlined button that wraps the existing Button widget with an additional class.
=> Outlined button

README.md, package.json
=> Add script to run functionals

package-lock.json, package.json, src/calendar/tests/unit/Calendar.ts, src/snackbar/index.tsx
=> Update Dojo Deps

src/tab-controller/tests/functional/TabController.ts, src/text-area/example/index.ts, src/text-area/tests/functional/Textarea.ts, src/text-input/tests/functional/TextInput.ts
**Type:** bug
Functional tests have been erroring out and causing disruption to development
=> Fixed problematic functional tests

src/text-input/index.ts, src/text-input/tests/unit/TextInput.tsx
Replaces: https://github.com/dojo/widgets/pull/736
Resolves: #740
=> Add min / max / step to text-input

package-lock.json, package.json
=> Upgrade to the alpha release of dojo 7

src/examples/src/widgets/grid/CustomCellRenderer.tsx, src/examples/src/widgets/grid/CustomFilterRenderer.tsx, src/examples/src/widgets/grid/CustomSortRenderer.tsx, src/examples/src/widgets/grid/EditableCells.tsx, src/examples/src/widgets/grid/Filtering.tsx, src/examples/src/widgets/grid/Restful.tsx, src/examples/src/widgets/grid/Sorting.tsx
=> Fix formatting on grid examples

.travis.yml, comment-deployments.sh, deploy.sh, now.json, package.json
Add some scripts that will hopefully deploy the example application to now.sh for pull requests and merges.
=> Deployment Scripts for Examples

src/calendar/CalendarCell.ts, src/calendar/DatePicker.ts, src/checkbox/index.ts, src/checkbox/tests/unit/Checkbox.ts, src/combobox/index.ts, src/combobox/tests/unit/ComboBox.ts, src/dialog/example/index.ts, src/dialog/index.ts, src/dialog/tests/unit/Dialog.ts, src/listbox/index.ts, src/listbox/tests/unit/Listbox.ts, src/meta/Focus.ts, src/radio/index.ts, src/radio/tests/unit/Radio.ts, src/range-slider/index.ts, src/range-slider/tests/unit/RangeSlider.ts, src/select/index.ts, src/select/tests/unit/Select.ts, src/slider/index.ts, src/slider/tests/unit/Slider.ts, src/text-area/index.ts, src/text-area/tests/unit/TextArea.tsx, src/text-input/index.ts, src/text-input/tests/unit/TextInput.tsx, src/time-picker/index.ts, src/time-picker/tests/unit/TimePicker.ts
Backport to v6 for https://github.com/dojo/widgets/pull/865
=> backport: Focus meta invalidation change (#865)

src/calendar/index.ts
Backport #863 to v6 to fix #862
=> backport: Fix calendar weekday cells

package-lock.json, src/calendar/index.ts, src/calendar/tests/unit/Calendar.ts
=> V6 - Support first day of week

package-lock.json, src/title-pane/index.ts, src/title-pane/tests/unit/TitlePane.spec.ts
Interface changed, so that users can style the property independently
Resolves #878
=> update interface of title-pane

src/card/index.tsx
=> Fix card not extending ThemedProperties

src/tab-controller/tests/unit/TabButton.spec.ts
**Type:** bug
Fixed broken test in master
=> Changed null to undefined for broken test

.travis.yml, deploy.sh, package.json
Add an extra deployment for examples that include the tests on pull requests.
=> Add extra test deployment

src/title-pane/index.ts, src/title-pane/tests/unit/TitlePane.ts
Backport of PR #878 for Issue #879
=> backport: update interface of title-pane (#878)

src/examples/src/config.ts, src/examples/src/widgets/outlined-button/DisabledSubmit.tsx, src/examples/src/widgets/outlined-button/ToggleButton.tsx, src/outlined-button/index.tsx, src/outlined-button/tests/unit/OutlinedButton.spec.tsx, src/theme/outlined-button.m.css, src/theme/outlined-button.m.css.d.ts
Similar to #855 but for outlined button. Still needs to be tested with themes (WIP).
Linked to: #847
=> change outlined to functional, compose themed classes

package-lock.json, src/grid/Body.ts, src/grid/Cell.ts, src/grid/Header.ts, src/grid/Row.ts, src/grid/example/index.ts, src/grid/index.ts, src/grid/interfaces.d.ts, src/grid/styles/header.m.css, src/grid/styles/header.m.css.d.ts, src/grid/tests/unit/Body.ts, src/grid/tests/unit/Cell.ts, src/grid/tests/unit/Grid.ts, src/grid/tests/unit/Header.ts, src/grid/tests/unit/Row.ts, src/theme/grid-header.m.css
=> V6 - Grid Resize Columns

package-lock.json, src/grid/PaginatedBody.ts, src/grid/PaginatedFooter.ts, src/grid/tests/unit/PaginatedBody.ts, src/grid/tests/unit/PaginatedFooter.ts
**Type:** bug
Backport of #969
=> V6 - Fix working with small datasets and pagination

src/grid/Body.ts, src/grid/PaginatedBody.ts, src/grid/Row.ts, src/grid/index.ts, src/grid/interfaces.d.ts, src/grid/processes.ts, src/grid/tests/unit/Body.ts, src/grid/tests/unit/Grid.ts, src/grid/tests/unit/PaginatedBody.ts, src/grid/tests/unit/Row.ts, src/grid/tests/unit/processes.ts, src/theme/grid-row.m.css, src/theme/grid-row.m.css.d.ts
=> V6 - Grid Row Selection

src/grid/README.md
Adds new features to grid readme
=> Add new features to grid readme

package-lock.json, src/examples/src/config.tsx, src/examples/src/widgets/grid/Advanced.tsx
Add an advanced grid usage example.
* Remote data fetching and updating
* Sorting and filtering
* Column resizing
* Row selection
* Traditional pagination
Resolves #???
=> Add Advanced Grid Example

package-lock.json, package.json, src/checkbox-group/tests/middleware.spec.tsx, src/form/index.tsx, src/form/middleware.ts, src/form/tests/unit/FormMiddleware.spec.tsx, src/middleware/tests/theme.spec.tsx, src/radio-group/tests/middleware.spec.ts, src/theme/radio-group.m.css
Update to `@dojo/framework@7.0.0-alpha.6`, `@dojo/cli-build-app@7.0.0-alpha.7` and latest `@dojo/parade`.
=> Update to dojo alpha 6

package-lock.json, src/middleware/bodyScroll.tsx, src/middleware/tests/bodyScroll.spec.tsx, src/popup/index.tsx
PR to disable body scroll via a middleware when using the popup.
Example of usage can be seen in the select demo.
Resolves #1023
=> Add body scroll middleware and use on popup

src/examples/src/config.tsx, src/examples/src/widgets/form/DisabledFieldsForm.tsx, src/examples/src/widgets/form/DisabledForm.tsx, src/examples/src/widgets/form/FillingForm.tsx, src/examples/src/widgets/form/InitialValueForm.tsx, src/examples/src/widgets/form/KitchenSinkForm.tsx, src/examples/src/widgets/form/RequiredFieldsForm.tsx, src/examples/src/widgets/form/ResettingForm.tsx, src/examples/src/widgets/form/SubmitForm.tsx, src/examples/src/widgets/form/Validation.tsx
- More examples for the form widget.
Resolves #980
=> Form examples

package-lock.json, src/common/tests/support/test-helpers.ts, src/grid/Cell.tsx, src/grid/Header.tsx, src/grid/tests/unit/Cell.spec.tsx, src/grid/tests/unit/Header.spec.tsx, src/text-input/index.tsx, src/text-input/tests/unit/TextInput.spec.tsx, src/theme/material/helper-text.m.css
=> Convert Text Input to functional widget

package-lock.json, src/accordion-pane/index.tsx, src/accordion-pane/tests/unit/AccordionPane.spec.tsx, src/examples/src/widgets/accordion-pane/Basic.tsx, src/examples/src/widgets/accordion-pane/Exclusive.tsx, src/theme/default/accordion-pane.m.css, src/theme/default/accordion-pane.m.css.d.ts, src/theme/material/accordion-pane.m.css, src/theme/material/accordion-pane.m.css.d.ts, src/theme/material/calendar.m.css, src/theme/material/select.m.css, src/theme/material/title-pane.m.css, src/theme/material/title-pane.m.css.d.ts, src/theme/material/variables.css
- Theme and adjustments to accordion pane / titlepane.
- Accordion pane _will_ need a re-write at some stage.
- Imports the correct mdc variables file
- Removes duplicated mdc variables
=> Material theme for TitlePane / Accordion

src/examples/src/config.tsx, src/examples/src/widgets/text-area/Disabled.tsx, src/examples/src/widgets/text-area/Label.tsx, src/text-area/index.tsx, src/text-area/tests/unit/TextArea.spec.tsx, src/text-input/index.tsx, src/theme/default/text-area.m.css, src/theme/default/text-area.m.css.d.ts, src/theme/material/text-area.m.css, src/theme/material/text-area.m.css.d.ts, src/theme/material/variables.css
**Note:** This PR relies on #990 being merged. Please review that one first
Resolves #992 
**Screenshot**
=> Material theme for TextArea

package-lock.json, package.json, src/examples/src/config.tsx
=> Update parade to 0.0.7

package-lock.json, package.json
Fixes travis by updating cli-test-intern / digdug version
=> Update @dojo/cli-test-intern version

src/examples/src/widgets/slider/Basic.tsx, src/examples/src/widgets/slider/DisabledSlider.tsx, src/examples/src/widgets/slider/SliderWithCustomOutput.tsx, src/examples/src/widgets/slider/SliderWithNoOutput.tsx, src/examples/src/widgets/slider/SliderWithValidityCheck.tsx, src/examples/src/widgets/slider/VerticalSlider.tsx, src/slider/index.tsx, src/slider/tests/unit/Slider.spec.tsx
=> Convert Slider to functional widget

src/constrained-input/index.tsx, src/popup/index.tsx, src/trigger-popup/index.tsx
This PR changes existing use of Pick / Exclude to use composition from base properties instead.
=> Prefer base properties over pick/exclude

src/examples/src/config.tsx, src/examples/src/widgets/combobox/Basic.tsx, src/examples/src/widgets/listbox/Basic.tsx
=> Remove combobox / listbox examples

src/popup/index.tsx
Updates popup positioning comment
Resolves #1090
=> Update popup positioning comment

package-lock.json, package.json
Base styles coming through without reset
Children being parsed
=> Update parade version

package-lock.json, package.json
=> update to latest parade

package-lock.json, package.json
Upgrade to the latest alpha releases.
=> update framework version

package-lock.json, package.json, src/examples/package.json
Update to the latest dojo deps and include globalize for parade in sandbox
=> Fix parade dep and update dojo deps

src/button/index.tsx, src/button/tests/unit/Button.spec.tsx
Updates `Button` widget to be function based.
Changes:
- Uses id from factory instead of uuid if no widgetId passed
- Converted to use factory
Resolves #1170
=> Refactor Button widget as functional

package-lock.json, package.json, src/accordion-pane/index.tsx, src/middleware/theme.tsx
Updates @dojo/framework to alpha.13
=> Update framework to alpha13

package-lock.json, src/theme/dojo/loading-indicator.m.css
**Type:** bug
Loading indicator overflows its parent.
=> Fix overflowing loading indicator

package-lock.json, src/text-area/index.tsx, src/text-input/index.tsx
Removes `onValue` callback when initialValue changes from textinput/area
Resolves #1225
=> Remove onValue for intitialValue

package-lock.json, src/calendar/date-utils.tsx, src/calendar/index.tsx, src/calendar/tests/unit/Calendar.spec.tsx, src/calendar/tests/unit/date-utils.spec.tsx, src/date-input/index.tsx, src/date-input/tests/unit/DateInput.spec.tsx, src/examples/src/config.tsx, src/examples/src/widgets/calendar/Basic.tsx, src/examples/src/widgets/calendar/CustomFirstWeekDay.tsx, src/examples/src/widgets/calendar/InitialMonthAndYear.tsx, src/examples/src/widgets/calendar/LimitedRange.tsx
**Note:** The work for this PR is complete but the unit tests still need to be updated.
This PR removes the following properties:
- month
- year
- selectedDate
- onDateSelect
- onMonthChange
- onYearChange
and adds the following properties:
- `initialValue?: Date` - The initial value of the calendar as a `Date` 
- `onValue?: (date: Date) => void` - handler called when the value of the calendar changes
- `initialMonth?: number` - The initial month to display on the calendar
- `onMonth?: (month: number) => void` - Handler called when the displayed month changes
- `initialYear?: number` - The initial year to display on the calendar
- `onYear?: (year: number) => void` - Handler called when the displayed year …
=> Uncontrolled Calendar

docs/V7-Migration-Guide.md
Initial Template / doc for V7 migration guide.
=> v7 migration guide template

docs/V7-Migration-Guide.md
Adds info about the calendar to the 6->7 migration guide.
Part of #1240
=> Calendar migration guide

docs/V7-Migration-Guide.md
Additions to migration guide
- add top sections
- remove new widgets
work towards: https://github.com/dojo/widgets/issues/1247
=> Migration guide

src/checkbox-group/index.tsx, src/checkbox-group/tests/CheckboxGroup.spec.tsx, src/checkbox/index.tsx, src/checkbox/tests/unit/Checkbox.spec.tsx, src/examples/src/config.tsx, src/examples/src/widgets/checkbox-group/CustomRenderer.tsx, src/examples/src/widgets/checkbox/CustomLabel.tsx, src/examples/src/widgets/checkbox/Disabled.tsx, src/examples/src/widgets/checkbox/Readonly.tsx, src/examples/src/widgets/dialog/CloseableDialog.tsx
=> Update checkbox to take its label as a child

.github/workflows/ci.yml, package-lock.json, package.json
Adds an `npm run build:tsc` command and calls it in CI to ensure that we haven't introduced type errors.
=> Add build:tsc command and step

package.json
=> Revert "Run TSC before dev"

package-lock.json, package.json, src/middleware/tests/theme.spec.tsx
Updates to latest framework version and fixes type errors.
=> Update framework version to v15

src/theme/material/range-slider.m.css
=> Fixed variable name

docs/V7-Migration-Guide.md
Migration guide for native select and select
Resolves #1240
=> Docs for select/native-select

src/examples/src/config.tsx, src/examples/src/widgets/time-picker/Controlled.tsx, src/time-picker/index.tsx, src/time-picker/tests/unit/TimePicker.spec.tsx
This depends on having a controlled text input
Resolves #1344
=> Controlled time picker

src/checkbox-group/tests/middleware.spec.tsx, src/form/middleware.ts, src/form/tests/unit/FormMiddleware.spec.tsx, src/grid/utils.ts, src/radio-group/tests/middleware.spec.ts
Fixes issues found when building and running tests with later versions of TS. Seemed to work fine when being used as a library. Tested using the example app.
Resolves #1372
=> TS forward compatibility

src/theme/material/avatar.m.css, src/theme/material/text-area.m.css, src/theme/material/tooltip.m.css, src/theme/material/variants/default.m.css
=> Align border radius and tooltip names

docs/V7-Migration-Guide.md
**Type:**  feature
**In Progress** -- Adds some missing information to the v7 migration guide. Formatting updates.
Resolves #1140
=> V7 migration guide improvements

.dojorc, package-lock.json, package.json, src/avatar/index.tsx, src/examples/src/config.tsx, src/examples/src/widgets/floating-action-button/Basic.tsx, src/examples/src/widgets/floating-action-button/Extended.tsx, src/floating-action-button/README.md, src/floating-action-button/index.tsx, src/floating-action-button/tests/unit/FloatingActionButton.spec.tsx, src/theme/default/floating-action-button.m.css, src/theme/default/floating-action-button.m.css.d.ts, src/theme/default/index.ts, src/theme/dojo/button.m.css, src/theme/dojo/button.m.css.d.ts, src/theme/dojo/floating-action-button.m.css, src/theme/dojo/floating-action-button.m.css.d.ts, src/theme/dojo/index.ts, src/theme/dojo/variants/default.m.css, src/theme/material/floating-action-button.m.css, src/theme/material/floating-action-button.m.css.d.ts, src/theme/material/index.ts
Adds a FAB component. The FAB component also provides a FAB icon that applies the proper font size for the icon so that it can be used alongside a label in the extended version without having to override the fontsize for the label or introduce complexity to child renderers.
Resolves #1382
=> Floating action button

src/theme/default/list-item.m.css, src/theme/default/menu-item.m.css, src/theme/dojo/list-item.m.css, src/theme/dojo/menu-item.m.css
Per title, adds pointer cursor for Default and Dojo themes.
Resolves #1417
=> Use pointer cursor for list and menu items

package-lock.json, package.json, src/middleware/tests/theme.spec.tsx, src/middleware/theme.tsx
Update to Dojo 7 Release Candidates
=> Update to Dojo 7 Release Candidates

src/theme/material/icon.m.css, src/theme/material/text-input.m.css
**Type:** bug
- Removes `clear` button from text-input in material theme
- Fixes material icons
=> IE11 Fixes

src/theme/material/calendar.m.css
Fixes material button background in IE in the calendar widget
=> IE: Fix calendar buttons

package-lock.json, package.json
Bumps to cli-test-intern `7.0.0-rc.2`
=> Update to latest cli-test-intern

src/theme/dojo/list-item.m.css, src/theme/dojo/loading-indicator.m.css, src/theme/dojo/menu-item.m.css
Fixes the height of the loading indicator when used on the `List` / `Menu`.
=> Fix the heights for the loading indicator in the list / menu

package-lock.json, package.json, src/popup/tests/Popup.spec.tsx
Update to dojo 7
waiting on parade release
=> Update to dojo 7

src/examples/src/widgets/select/Controlled.tsx, src/examples/src/widgets/select/CustomRenderer.tsx
Fixes label for custom renderer and controlled select.
=> Change the select example labels to match the titles

README.md
**Type:** document
Fix  styling issue on README.
=> Add missing backticks in README

src/checkbox/README.md, src/radio/README.md
**Type:** bug
Aligns and corrects the checkbox / radio readme files.
Resolves #1487
=> fix readmes

src/typeahead/index.tsx, src/typeahead/tests/unit/Typeahead.spec.tsx
Removes the autocomplete from the text input used by typeahead
Resolves: #1499
=> Set typeahead autocomplete to false

src/theme/default/list-item.m.css
Current default list-item selected background color is too dark. This lightens it.
=> Change default list-item selected background to lightgrey

package-lock.json, package.json, src/grid/styles/grid.m.css, src/two-column-layout/tests/TwoColumnLayout.spec.tsx
=> v7 Backports: build app version and grid-height fix

src/list/index.tsx, src/list/tests/List.spec.tsx, src/typeahead/index.tsx, src/typeahead/tests/unit/Typeahead.spec.tsx
=> V7 Backport - List / Typeahead

src/theme/default/button.m.css
=> Button: fix typo in theme CSS

.dojorc, src/examples/src/config.tsx, src/examples/src/widgets/rate/AllowHalf.tsx, src/examples/src/widgets/rate/Basic.tsx, src/examples/src/widgets/rate/Controlled.tsx, src/examples/src/widgets/rate/CustomIcon.tsx, src/examples/src/widgets/rate/ReadOnly.tsx, src/rate/README.md, src/rate/index.tsx, src/rate/rate.m.css, src/rate/rate.m.css.d.ts, src/rate/tests/Rate.spec.tsx, src/theme/default/index.ts, src/theme/default/rate.m.css, src/theme/default/rate.m.css.d.ts, src/theme/dojo/index.ts, src/theme/dojo/rate.m.css, src/theme/dojo/rate.m.css.d.ts, src/theme/material/index.ts, src/theme/material/rate.m.css, src/theme/material/rate.m.css.d.ts, src/theme/material/variants/dark.m.css, src/theme/material/variants/default.m.css
**Type:** new widget
Adds a rate widget with customisable icons
=> Star Rating Widget

src/slide-pane/styles/slide-pane.m.css, src/theme/dojo/slide-pane.m.css, src/theme/dojo/slide-pane.m.css.d.ts, src/theme/material/slide-pane.m.css, src/theme/material/slide-pane.m.css.d.ts
Backport of #1544 to fix #1522 for v7.
=> v7 backport - slidepane fix (#1544)

src/theme/material/header.m.css
Uses primary on dark colour for material header title / actions
Resolves: #1553
=> Use primary dark for header title / actions on material header

package-lock.json, src/common/tests/support/test-helpers.ts, src/date-input/index.tsx, src/date-input/tests/unit/DateInput.spec.tsx, src/examples/src/config.tsx, src/examples/src/widgets/date-input/Disabled.tsx, src/examples/src/widgets/date-input/ReadOnly.tsx
**Type:** bug
Backport of #1601
=> V7 Backport: Date disabled/readonly

src/theme/dojo/button.m.css.d.ts, src/theme/dojo/outlined-button.m.css.d.ts, src/theme/dojo/raised-button.m.css.d.ts, src/theme/material/button.m.css.d.ts, src/theme/material/outlined-button.m.css.d.ts, src/theme/material/raised-button.m.css.d.ts
Fixing bad .d.ts files caused by button kind pr.
=> fixing button kind styles
