dojo/widgets

- README.md
**Type:** typo
The link to the `dojo/widget-core` github repo has been fixed.
> Fix link to dojo/widget-core

- package.json
- tsconfig.json
- typings.json
Remove the symbol shim typings and update to the latest dojo 2 deps.
Related to https://github.com/dojo/meta/issues/113
> Remove symbol-shim typings

- src/label/Label.ts
- src/label/example/index.ts
- src/label/tests/unit/Label.ts
**Type:** bug
Since we're removing `this.classes().get()`, Label's `properties.classes` should be a `ClassesFunctionChain` instead of `ClassNameFlags`
> Updated label classes type after removal of .get()

- src/dialog/Dialog.ts
- src/dialog/tests/unit/Dialog.ts
**Type:** bug
This PR fixes an issue with the Dialog and it's `role` property. It exported an enum to use, but it should've exported a string literal (which also provides intellisense.)
Resolves #69
> Dialog "role"

- src/textarea/example/index.ts
- src/textinput/example/index.ts
Updates textinput and textarea example pages to have all widgets be fully controlled by the parent
> textinput and textarea examples should be fully controlled

- src/slidepane/SlidePane.ts
- src/slidepane/styles/slidePane.m.css
- src/slidepane/styles/slidePane.m.css.d.ts
Provides a means to target the root node for the slidepane. Useful for setting the`z-index` such that it appears above other elements.
> Added root class to slidepane root

- src/button/Button.ts
- src/button/example/index.ts
- src/button/tests/unit/Button.ts
**Type:** bug
Switches `hasPopup` for `popup`, which also allows you to pass in information about the popup (current expanded/collapsed state and id).
Resolves #108
> Add aria-controls and aria-expanded to popup

- src/dialog/Dialog.ts
Updated Dialog `role` string literal type to be `RoleType` instead of `Role`
Resolves #106
> Role -> RoleType

- src/checkbox/Checkbox.ts
- src/radio/Radio.ts
- src/select/Select.ts
- src/slider/Slider.ts
- src/textarea/Textarea.ts
- src/textinput/TextInput.ts
**Type:** bug
- Updates widgets that use `aria-invalid` to only show the property when it is set to `true`. Previously, widgets were displaying `aria-invalid="undefined"`.
- Also updates Select option id's to be correctly referenced in `aria-activedescendant`.
> Aria cleanup

- src/common/tests/intern.ts
**Type:** bug
Should skip the generated `css.js` themes files for coverage.
> Skip theme `css.js` files for coverage

- src/common/tests/intern.ts
**Type:** bug
Revert to Safari 9.1 as Safari 10 is not working on browserstack
> Revert to use safari 9.1

- src/dialog/Dialog.ts
- src/dialog/styles/dialog.m.css
- src/dialog/styles/dialog.m.css.d.ts
- src/dialog/tests/unit/Dialog.ts
Adds `root` class to widgets that are missing it.
`Label` still missing root but can be added in PR that addresses the `classes` property label currently accepts.
Resolves #75
> Added root class to dialog

- package.json
- src/checkbox/Checkbox.ts
- src/combobox/ComboBox.ts
- src/combobox/ResultMenu.ts
- src/radio/Radio.ts
- src/select/Select.ts
- src/slider/Slider.ts
- src/textarea/Textarea.ts
- src/textinput/TextInput.ts
Prepping for the next release of `widget-core` that removes `bind` from both the `v()` and `w()` property interfaces. `bind` will automatically be added to all nodes from a `render` call using an `afterRender` in `WidgetBase`.
This means there is no way to pass `bind` when trying to assert with test-extras, so https://github.com/dojo/test-extras/issues/38 will need to be addressed first.
> Remove bind references in v() and w() calls

- src/common/styles/widgets.css.d.ts
- src/slidepane/SlidePane.ts
- src/slidepane/tests/unit/SlidePane.ts
- src/themes/dojo/slidePane.m.css
- src/themes/dojo/slidePane.m.css.d.ts
**Type:** bug
Remove direct DOM manipulation from `SlidePane` so that its animations and functionality do not depend directly on `src/slidepane/styles/slidePane.m.css`.
Previously, `SlidePane` treated the `open`, `left`, and `right` CSS classes as fixed classes. However, this made it impossible for themes to specify combinations like `left.slideIn`, since the corresponding `left` class in the generated CSS is different than the fixed class actually applied to the DOM node. As such, `open`, `left`, and `right` were downgraded to normal classes.
Resolves #129
> Fix slidepane animations with custom theme.

- src/common/tests/functional/all.ts
- src/common/tests/intern.ts
- src/slidepane/tests/functional/SlidePane.ts
Adds functional tests for `SlidePane`. Swipe tests are skipped for both Firefox and Edge since the FirefoxDriver is extremely limited, and since the MS Edge driver does not handle mouse movements correctly (in multiple independent tests I verified that Edge reports different `MouseEvent#pageX` values then those passed to the `moveMouseTo` methods).
Resolves #157
> Add `SlidePane` functional tests.

- src/slidepane/SlidePane.ts
**Type:** bug
After reopening a `SlidePane`, the CSS `transform` property should be reset to avoid interfering with animations.
> Fix: clear SlidePane transform on reopen.

- src/combobox/ComboBox.ts
- src/dialog/Dialog.ts
- src/slider/Slider.ts
- src/tabpane/TabPane.ts
**Type:** bug
This PR makes `uuid` usage more efficient throughout existing components.
Resolves #207
> Update `uuid` usage throughout existing components

- src/slider/styles/slider.m.css
**Type:** bug
`display` should not have been set to `inline-block`. It needs to be `block` to fill the space it is provided with.
> Fix error in previous slider pr

- src/button/example/index.ts
- src/checkbox/example/index.ts
- src/combobox/example/index.ts
- src/dialog/example/index.ts
- src/select/example/index.ts
- src/slidepane/example/index.ts
- src/slider/example/index.ts
- src/splitpane/example/index.ts
- src/tabpane/example/index.ts
- src/textarea/example/index.ts
- src/textinput/example/index.ts
This PR removes once-necessary type casting from examples. The issue was evident when grabbing values from state and passing them to child components as properties.
Resolves #217
> Remove unnecessary type casting in examples

- src/dialog/Dialog.ts
- src/dialog/README.md
- src/dialog/createDialogElement.ts
- src/dialog/tests/unit/Dialog.ts
This PR adds an initial readme for the Dialog based on Andy's template. The aim was to include a general description, pertinent a11y and i18n information, and to show common example uses, while avoiding API documentation. This PR also adds one property to the Dialog for i18n, a shortcoming discovered during the readme authoring.
Resolves #183
> Dialog readme and i18n update

- src/combobox/ComboBox.ts
- src/select/Select.ts
**Type:** bug
Since `onPropertiesChanged` won't fire on initial render if there are no properties passed, registry creation should happen in the constructor. Adds custom `@diffProperty` decorators for now, until https://github.com/dojo/widget-core/issues/567 is resolved.
> Fix registry creation in widgets

- src/button/Button.ts
- src/button/tests/unit/Button.ts
Replaces: https://github.com/dojo/widgets/pull/133
Resolves #135
> Button test updates

- src/button/Button.ts
- src/button/example/index.ts
- src/button/tests/unit/Button.ts
Button had been using a `content` property to set `innerHTML`, but this approach is limiting and outdated. I would prefer to use `this.children`, which is more in line with our other widgets and will make things like adding icons much easier.
> Update Button to use `this.children`

- src/button/README.md
- src/button/example/index.ts
Resolves #180, adds Button README and fixes event typings on the example page. The content depends on the changes in #230
> Button README

- src/slider/README.md
- src/slider/example/index.ts
Resolves #189, adds Slider readme and fixes event typings on the example page.
> Slider README

- src/tabpane/README.md
> TabPane README

- src/tabpane/TabButton.ts
- src/tabpane/TabPane.ts
- src/tabpane/tests/unit/TabButton.ts
**Type:** bug
TabPane was stealing focus, updated it to use the same method of setting focus used in other widgets.
> updated focus management for tabpane

- package.json
- src/button/example/index.ts
- src/calendar/Calendar.ts
- src/calendar/example/index.ts
- src/calendar/tests/unit/MonthPicker.ts
- src/checkbox/example/index.ts
- src/combobox/ComboBox.ts
- src/combobox/example/index.ts
- src/common/example/index.html
- src/common/example/index.ts
- src/dialog/example/index.ts
- src/label/example/index.ts
- src/radio/example/index.ts
- src/select/Select.ts
- src/select/example/index.ts
- src/select/tests/unit/Select.ts
- src/slidepane/example/index.ts
- src/slider/example/index.ts
- src/splitpane/example/index.ts
- src/tabpane/example/index.ts
- src/textarea/example/index.ts
- src/textinput/example/index.ts
- src/timepicker/TimePicker.ts
- src/timepicker/example/index.ts
- src/titlepane/example/index.ts
- src/titlepane/tests/unit/TitlePane.ts
Upgrade for breaking changes expected in the next release of widget-core.
Depends on `widget-core` being released.
> Changes for next widget-core release

- Gruntfile.js
- src/common/example/example.css
- src/common/example/index.html
- src/tabpane/TabButton.ts
- src/timepicker/TimePicker.ts
This PR moves removes `common/styles/widgets.css` and adds a new `common/example/example.css` file, the name and location of which more clearly denote that this pattern should not be followed. As per @kitsonk and @tomdye, we should eventually consider moving examples out of widgets entirely, as they're a unrealistic example of Dojo 2 application code.
Resolves #240
> widgets.css -> example.css

- src/radio/Radio.ts
- src/radio/styles/radio.m.css
- src/radio/styles/radio.m.css.d.ts
- src/radio/tests/unit/Radio.ts
- src/themes/dojo/radio.m.css
- src/themes/dojo/variables.css
This PR adds a base theme for the radio widget. In doing so, a `.focused` class was needed on the root node. It seems a common enough styling case to add it for at least the radio and checkbox widgets.
> Radio Theme

- src/themes/dojo/tabPane.m.css
- src/themes/dojo/variables.css
This PR adds an initial theme for the TabPane component.
> Theme: TabPane

- src/common/example/index.html
- src/slider/Slider.ts
- src/slider/example/index.ts
- src/slider/styles/slider.m.css
- src/slider/styles/slider.m.css.d.ts
- src/slider/tests/unit/Slider.ts
- src/themes/dojo/slider.m.css
- src/themes/dojo/variables.css
Adds base theme for the slider widget. Modified the widget to include a boolean property to create a tooltip tied to the slider handle.
Also added body padding to examples.
> Slider Theme

- src/slider/Slider.ts
- src/slider/tests/unit/Slider.ts
**Type:** bug
This PR updates the Slider component so it never renders a value higher than its `max` or lower than its `min`.
Resolves #259
> Slider: min / max value fix

- src/splitpane/styles/splitPane.m.css
- src/themes/dojo/splitPane.m.css
- tscommand-bdde2fd3.tmp.txt
This PR adds an initial theme for the SplitPane component.
> Theme: SplitPane

- src/calendar/tests/unit/CalendarCell.ts
- src/calendar/tests/unit/MonthPicker.ts
- src/combobox/ComboBox.ts
- src/slidepane/tests/unit/SlidePane.ts
- src/splitpane/tests/unit/SplitPane.ts
- src/timepicker/tests/unit/TimePicker.ts
- src/titlepane/tests/unit/TitlePane.ts
Upgrade to latest widget-core, required release.
> widget-core upgrade

- src/slider/Slider.ts
- src/slider/tests/unit/Slider.ts
**Type:** bug
The slider widget was calculating thumb position incorrectly when the minimum value was not zero
> Fix slider thumb position on non-zero mins

- src/combobox/ResultMenu.ts
- src/label/Label.ts
Registry support is now built into [built into](https://github.com/dojo/widget-core/pull/636/files) `WidgetBase`.
**DO NOT MERGE**
Related To https://github.com/dojo/widget-core/issues/613
> Registry support built into WidgetBase

- src/checkbox/tests/unit/Checkbox.ts
> Checkbox unit tests updated to use test-extras

- src/common/tests/unit/main.ts
- src/slider/Slider.ts
- src/slider/tests/unit/Slider.ts
Resolves #144 
Also updates string casting to consistently use template literals
> Slider unit tests updated to use test-extras

- src/dialog/tests/unit/Dialog.ts
> Dialog unit tests updated to use test-extras

- .travis.yml
- Gruntfile.js
**Type:** bug
`grunt-dojo2` now looks for `intern${version}` instead of `intern` in config options.
> Update intern to intern3 in grunt config

- src/checkbox/Checkbox.ts
- src/checkbox/tests/unit/Checkbox.ts
- src/combobox/ComboBox.ts
- src/combobox/createComboBoxElement.ts
- src/label/Label.ts
- src/label/tests/unit/Label.ts
- src/radio/Radio.ts
- src/radio/tests/unit/Radio.ts
- src/select/Select.ts
- src/select/tests/unit/Select.ts
- src/slider/Slider.ts
- src/slider/tests/unit/Slider.ts
- src/textarea/Textarea.ts
- src/textarea/tests/unit/Textarea.ts
- src/textinput/TextInput.ts
- src/textinput/tests/unit/TextInput.ts
- src/timepicker/TimePicker.ts
- src/timepicker/tests/unit/TimePicker.ts
The HTML `form` attribute has been pulled from spec, so I think it makes sense to remove it. Additionally, based on chatting with other a11y folks, I think it makes sense to provide the option to explicitly associate a Label with a form field with `id`/`for`. In the past some screen readers had variable behavior with nested form fields, and having the `for` attribute provides more flexibility to the widget.
> Label: add `for` and remove `form`

- src/themes/dojo/checkbox.m.css
- src/themes/dojo/radio.m.css
**Type:** bug
Themed radio and checkbox inputs should be visible and toggle-able without a label. I added a min-height to the root element and removed `z-index: -1` so the `<input>` element sits on top of the styled control.
> Radio and Checkbox interaction with no label

- package.json
- src/calendar/Calendar.ts
- src/calendar/README.md
- src/calendar/createCalendarElement.ts
- src/calendar/tests/unit/Calendar.ts
- src/combobox/ComboBox.ts
- src/combobox/README.md
- src/combobox/ResultMenu.ts
- src/combobox/createComboBoxElement.ts
- src/combobox/example/index.ts
- src/combobox/tests/unit/ComboBox.ts
- src/combobox/tests/unit/ResultMenu.ts
- src/label/Label.ts
- src/select/Select.ts
- src/select/example/index.ts
- src/select/tests/unit/Select.ts
- src/timepicker/TimePicker.ts
- src/timepicker/tests/unit/TimePicker.ts
It's that time of year again where we need to update widgets inline with breaking changes from widget-core.
Main changes being `registry` is no longer an accepted property for `WidgetBase` - Have updated to take the constructor directory and use.
Requires release of test-extras
> Update for @dojo/widget-core changes

- src/splitpane/styles/splitPane.m.css
`background` on fixed class was being used over `background-color` in the theme. Moved the background to the themeable class instead.
Resolves #300
> 300 - Fix splitpane border

- src/slidepane/styles/slidePane.m.css
**Type:** bug
The SlidePane's main content pane was fixed with no z-index. While #335 will consolidate all z-indexes across the component base, this fix at least allows SlidePane to render properly (for example, on the showcase page) until the global z-index pattern is sorted.
Resolves #329
> Add z-index to SlidePane content

- src/dialog/Dialog.ts
- src/dialog/tests/unit/Dialog.ts
**Type:** bug
Close Dialog when escape key is pressed
Resolves #327
> 372 - Escape key closes dialog

- src/slider/example/index.ts
- src/themes/dojo/slider.m.css
- src/themes/dojo/variables.css
**Type:** bug
Resolves #328 
Updated theme styles to make the invisible input controls larger. I also added `onChange` in the example page to fix a VO + Safari issue where the visual UI didn't update while interacting with the input.
> Slider dragging bug

- src/accordionpane/tests/functional/AccordionPane.ts
- src/button/Button.ts
- src/button/tests/functional/Button.ts
- src/calendar/Calendar.ts
- src/calendar/CalendarCell.ts
- src/calendar/DatePicker.ts
- src/calendar/createCalendarElement.ts
- src/calendar/tests/unit/Calendar.ts
- src/checkbox/Checkbox.ts
- src/dialog/Dialog.ts
- src/radio/Radio.ts
- src/slidepane/SlidePane.ts
- src/slider/Slider.ts
- src/splitpane/SplitPane.ts
- src/tabcontroller/TabButton.ts
- src/tabcontroller/TabController.ts
- src/tabcontroller/tests/unit/TabButton.ts
- src/textarea/Textarea.ts
- src/textinput/TextInput.ts
- src/themes/dojo/titlePane.m.css
- src/timepicker/TimePicker.ts
- src/titlepane/TitlePane.ts
- src/titlepane/tests/functional/TitlePane.ts
- src/titlepane/tests/unit/TitlePane.ts
Resolves #316 
Makes widgets more easily extensible by simplifying the render code, particularly addressing these points from the issue:
- break out large chunks of rendered dom
- state classes are returned in a function
- icons are broken out
- inline styles are calculated separately
> Simplify widget render

- src/accordionpane/README.md
- src/accordionpane/createAccordionPaneElement.ts
**Type:** bug
Adds a README for AccordionPane (mostly placeholder, like other components) and a proper custom element descriptor.
Resolves #364
> Add AccordionPane README and custom element descriptor

- .travis.yml
Adds `grunt dist` to the `travis.yml`
> add `grunt dist` to travis.yml

- src/common/tests/functional/all.ts
- src/textarea/example/index.ts
- src/textarea/tests/functional/Textarea.ts
> Textarea functional tests

- src/common/tests/functional/all.ts
- src/slider/example/index.ts
- src/slider/tests/functional/Slider.ts
Adds basic functional tests for `Dialog` based on lzhoucs's PR https://github.com/dojo/widgets/pull/178 with rebasing and updates.
Resolves #158
> Slider functional tests

- src/common/tests/functional/all.ts
- src/timepicker/example/index.ts
- src/timepicker/tests/functional/TimePicker.ts
Wraps example tests with identifiers. Adds functional tests.
Resolves #162
> Add TimePicker functional tests

- src/tooltip/Tooltip.ts
- src/tooltip/tests/unit/Tooltip.ts
**Type:** bug
Adds keys to the nodes created by tooltip so that they are uniquely identifiable.
Resolves #380
> Add keys for tooltip nodes so that they can be uniquely identified

- package-lock.json
- src/accordionpane/createAccordionPaneElement.ts
- src/titlepane/createTitlePaneElement.ts
**Type:** bug
This PR updates the tag name of the AccordionPane custom element and the `onRequestClose` event name of the TitlePane custom element.
Resolves #383, #384
> Custom element fixes

- src/accordionpane/createAccordionPaneElement.ts
- src/calendar/createCalendarElement.ts
- src/combobox/createComboBoxElement.ts
- src/dialog/createDialogElement.ts
- src/slidepane/createSlidePaneElement.ts
- src/splitpane/createSplitPaneElement.ts
- src/tabcontroller/createTabControllerElement.ts
- src/tabcontroller/createTabElement.ts
- src/titlepane/createTitlePaneElement.ts
- src/tooltip/createTooltipElement.ts
**Type:** bug
This PR exposes a `theme` property on each applicable custom element descriptor so they can be properly themed.
Resolves #382
> Themeable custom elements

- src/themes/dojo/comboBox.m.css
**Type:** bug
ComboBox now uses similar styles to Select. Resolves #354
> Increase font size, decrease padding for dropdown arrow

- package-lock.json
- package.json
- src/slider/tests/functional/Slider.ts
**Type:** bug
Intern now uses the new typings for chai which conflict with the pinned ones.
> Remove dependency on chai and use what comes with Intern

- src/calendar/Calendar.ts
- src/calendar/tests/unit/Calendar.ts
- src/tabcontroller/TabController.ts
- src/tabcontroller/tests/unit/TabController.ts
- src/themes/dojo/tabController.m.css
**Type:** bug
Resolves #400, removes destructuring assignment for `theme` in both TabController and Calendar.
> Fix destructured theme assignment blocking theme injector

- intern.json
- package-lock.json
- package.json
- src/calendar/nls/Calendar.ts
- src/common/nls/common.ts
Upgrade dojo dependencies for widget-core and i18n and convert the nls bundles to the new format.
Resolves #415
> Convert nls bundles for new Bundle formatting

- src/toolbar/README.md
Simple typo in the Toolbar readme example
> fix typo in Toolbar readme example

- src/checkbox/Checkbox.ts
- src/checkbox/tests/unit/Checkbox.ts
- src/combobox/ComboBox.ts
- src/combobox/tests/unit/ComboBox.ts
- src/common/interfaces.d.ts
- src/listbox/tests/functional/Listbox.ts
- src/radio/Radio.ts
- src/radio/tests/unit/Radio.ts
- src/select/Select.ts
- src/select/tests/unit/Select.ts
- src/slider/Slider.ts
- src/slider/tests/unit/Slider.ts
- src/splitpane/tests/functional/SplitPane.ts
- src/textarea/Textarea.ts
- src/textarea/tests/unit/Textarea.ts
- src/textinput/TextInput.ts
- src/textinput/tests/unit/TextInput.ts
- src/timepicker/TimePicker.ts
- src/timepicker/tests/unit/TimePicker.ts
Resolves #430, adds an `id` prop to form widgets so anyone wishing to use their own label may do so
> Add `id` property to form widgets

- package-lock.json
- package.json
- src/calendar/CalendarCell.ts
- src/calendar/DatePicker.ts
- src/calendar/tests/unit/DatePicker.ts
- src/dialog/Dialog.ts
- src/dialog/example/index.ts
- src/dialog/tests/unit/Dialog.ts
- src/select/Select.ts
- src/tabcontroller/TabButton.ts
- src/tabcontroller/tests/unit/TabButton.ts
- src/theme/dialog/dialog.m.css
Removes directly accessing elements in `onElementUpdated`/`onElementCreated` where possible in favor of the Focus meta. It is still necessary to use the old method for reaching into child widgets and focusing on VNode creation.
> Update widgets to use Focus meta

- src/slider/Slider.ts
- src/slider/tests/unit/Slider.ts
Massive change to disable focus from `<output>` tag so Edge doesn't jump to it when navigating with Tab.
Issue #402
> Explicitly disabling focus from output tag for Edge

- src/button/Button.ts
- src/calendar/Calendar.ts
- src/calendar/CalendarCell.ts
- src/calendar/tests/unit/Calendar.ts
- src/checkbox/Checkbox.ts
- src/checkbox/example/index.ts
- src/checkbox/tests/unit/Checkbox.ts
- src/combobox/ComboBox.ts
- src/combobox/tests/unit/ComboBox.ts
- src/common/interfaces.d.ts
- src/common/tests/support/test-helpers.ts
- src/enhancedtextinput/example/index.ts
- src/enhancedtextinput/tests/unit/EnhancedTextInput.ts
- src/radio/Radio.ts
- src/radio/example/index.ts
- src/radio/tests/unit/Radio.ts
- src/slider/Slider.ts
- src/slider/example/index.ts
- src/slider/tests/unit/Slider.ts
- src/textarea/Textarea.ts
- src/textarea/example/index.ts
- src/textarea/tests/unit/Textarea.ts
- src/textinput/TextInput.ts
- src/textinput/example/index.ts
- src/textinput/tests/unit/TextInput.ts
Removes the dom events from widget callbacks.
Widgets not callback with data more appropriate to the widget type. ie. 
- inputs return `value:string`
- checkbox returns `value: string` and `checked: boolean`.
Resolves #302
> Remove dom event from widget callbacks

- intern.json
Limit functional test running to chrome only via browserstack
Resolves #487
> Run CI functional tests on chrome only

- .travis.yml
- intern.json
- package.json
- Switches the CI to run functional tests in headless chrome, eliminating the need to use browserstack for PR builds. This brings the time down to ~5minutes for a PR builds.
- Re-instates the browserstack / saucelabs configs for future use in a `nightly` build.
Requires: https://github.com/dojo/grunt-dojo2/pull/193 
Related to #488 and #489
> Use chrome headless for ci testing

- src/split-pane/index.ts
- src/toolbar/README.md
- src/toolbar/example/index.ts
- src/toolbar/index.ts
- src/toolbar/tests/unit/Toolbar.ts
**Type:** bug
Toolbar takes a `title` property that causes problems when it is used as a custom element.
Changing this to `heading` fixes this and standardises the heading that is shown on both the toolbar and the popup menu when the toolbar is collapsed.
This change means that toolbar no longer takes a `DNode` as it's title / heading, just a string.
> Use toolbarTitle instead of title in toolbar

- README.md
**Type:** bug
Update some widget URLs and include info on viewing widgets locally. 
Resolves https://github.com/dojo/widgets/issues/500 and https://github.com/dojo/widgets/issues/501
> Update the widget URLs in the main readme and include info on viewing widget examples locally

- src/select/index.ts
**Type:** bug
Adds missing `value` attribute for `Select`
> Add missing value attribute for select

- src/split-pane/index.ts
- src/split-pane/tests/unit/SplitPane.ts
**Type:** bug
Fixes an issue where `autopx` was being set as width instead of `auto` when collapsing the split pane.
> Fix auto width on split-pane

- .dojorc
Adds missing icon widget to dojorc so it can be used as a custom-element
> Add icon custom-element to dojorc

- src/checkbox/index.ts
- src/radio/index.ts
- `mode` is now a string, so should be set as an attribute on checkbox.
- `name` was missing from radio.
> Add missing text attributes to checkbox and radio

- src/calendar/DatePicker.ts
- src/checkbox/index.ts
- src/combobox/index.ts
- src/common/util.ts
- src/slide-pane/index.ts
- src/split-pane/index.ts
- src/tab-controller/index.ts
- src/tooltip/index.ts
**Type:** bug
Removes keyword `const` from declaring enums.
Resolves #524
> Remove const keyword when declaring enums

- src/slider/index.ts
- src/slider/styles/slider.m.css
- src/slider/styles/slider.m.css.d.ts
- src/slider/tests/unit/Slider.ts
- src/theme/slider.m.css
- src/theme/slider.m.css.d.ts
Making `.outputTooltip` class themable by removing it from the fixed CSS and adding it to the theme CSS.
Resolves #533
> Making .outputTooltip class on slider themable

- src/split-pane/index.ts
**Type:** bug
From what I understand, Firefox is interpreting this interaction as "the user wants to drag this image somewhere" which is more obvious in this screenshot:
Assuming this is the "default" interaction, I called `preventDefault()` on the event.
I'm attaching a small project [541.zip](https://github.com/dojo/widgets/files/1948922/541.zip) that should show this in action with and without `preventDefault()` applied to the event. You don't have to move your mouse particularly fast or do anything out of the ordinary. Just drag/move/drop until it happens – you don't even have to move your mouse in between drag/drops. By default, it won't apply `preventDefault()` but if you set the global `testPreventDefault = true` it will …
> Prevent default mouse down behavior

- src/calendar/DatePicker.ts
- src/calendar/index.ts
- src/calendar/tests/functional/Calendar.ts
- src/calendar/tests/unit/DatePicker.ts
- src/split-pane/styles/split-pane.m.css
**Type:** bug
Add invalidation when the datepicker dropdown is opened and closed, fix radio change event bubbling to popup button
Resolves #535
> Calendar bugfixes

- src/dialog/index.ts
- src/dialog/tests/unit/Dialog.ts
**Type:** bug
Resolves #537 
Modal dialogs trap focus, non-modal dialogs close on blur
> Dialog focus handling

- package-lock.json
- src/calendar/tests/unit/Calendar.ts
- src/combobox/tests/unit/ComboBox.ts
- src/common/example/index.html
- src/dialog/tests/unit/Dialog.ts
- src/slide-pane/tests/unit/SlidePane.ts
- src/tab-controller/tests/unit/TabButton.ts
- src/toolbar/tests/unit/Toolbar.ts
**Type:** bug
Necessary to fix failing tests: updates the path to the dojo loader so examples and functional tests load, and updates unit tests as the I18n mixin no longer adds `dir` and `lang` attributes when not set (see https://github.com/dojo/widget-core/pull/951).
> Fix loader path and i18n properties to fix failing tests

- src/slider/example/index.ts
- src/slider/index.ts
- src/slider/tests/unit/Slider.ts
Adds `showOutput` option to `Slider` so you can remove the output node from the rendering. Same property as `Progress`.
Resolves #559
> showOutput code and tests

- src/combobox/index.ts
- src/combobox/tests/unit/ComboBox.ts
Both `Select` and `Listbox` allow a `DNode` return type for `getOptionLabel`. It makes sense to update `ComboBox` to allow the same.
> Change comobobox getResultLabel type to match select and listbox

- src/combobox/index.ts
- src/combobox/tests/unit/ComboBox.ts
Resolves #485 
Adds the onResultSelect event, called when enter/select is pressed and via the nested Listbox `onOptionSelect` event.
> Add onResultSelect Event to ComboBox

- src/theme/listbox.m.css
**Type:** bug
Resolves #589, updates focus style to contrast with the options' selected style
> Update listbox option focus styles

- src/grid/tests/unit/widgets/Header.ts
- src/grid/widgets/Header.ts
- src/grid/widgets/styles/Header.m.css
- src/grid/widgets/styles/Header.m.css.d.ts
Resolves #587 
Things to follow up on:
- is `search` the correct input type for a filtering input?
- the filter input's label text is included in the column header text read for each cell in its column, and does not seem to be overridable by `aria-label` or `aria-labelledby` on the column header element.
> Accessible grid sorting and filtering

- src/grid/README.md
- src/grid/example/index.ts
- src/grid/tests/unit/widgets/Body.ts
- src/grid/tests/unit/widgets/Grid.ts
- src/grid/tests/unit/widgets/Header.ts
- src/grid/widgets/Body.ts
- src/grid/widgets/Grid.ts
- src/grid/widgets/Header.ts
- src/grid/widgets/styles/Grid.m.css
- src/grid/widgets/styles/Grid.m.css.d.ts
- src/grid/widgets/styles/Header.m.css
- src/grid/widgets/styles/Header.m.css.d.ts
- src/grid/widgets/styles/PlaceholderRow.m.css
- src/grid/widgets/styles/Row.m.css
**Type:** bug
Addresses #584, removes hard-coded height values for header and footer in grid row calculations in favor of an explicit height property.
> Grid height property

- src/grid/tests/unit/widgets/Body.ts
- src/grid/tests/unit/widgets/Grid.ts
- src/grid/tests/unit/widgets/Header.ts
- src/grid/tests/unit/widgets/Row.ts
- src/grid/widgets/Body.ts
- src/grid/widgets/Grid.ts
- src/grid/widgets/Header.ts
- src/grid/widgets/Row.ts
**Type:** bug
Resolves #585 
Adds ARIA attributes for row count and index to handle not all rows existing in the DOM. Also adds ARIA attribute for column sorting.
Updates `pageChange` page numbering logic. Previously, when the grid fetched more rows at once than existing in a single page, it was possible to never land on the first page.
> Add paging aria semantics, update pageChange

- src/theme/slider.m.css
Having the entire slider focused is causing issues with combining sliders to [create a range slider](https://github.com/dojo/widgets/issues/554).
Moving the focus ring from the entire slider input:
to the just the thumb:
> Slider focus

- src/button/index.ts
- src/button/tests/unit/Button.ts
- src/combobox/index.ts
- src/combobox/tests/functional/ComboBox.ts
- src/combobox/tests/unit/ComboBox.ts
- src/common/tests/support/test-helpers.ts
- src/enhanced-text-input/index.ts
- src/enhanced-text-input/tests/unit/EnhancedTextInput.ts
- src/grid/tests/unit/widgets/Cell.ts
- src/grid/utils.ts
- src/grid/widgets/Cell.ts
- src/text-input/index.ts
- src/text-input/tests/unit/TextInput.ts
- Updates the grid cell to use TextInput and Button widgets
- Improves focus handling for cell editing
- Improves focus handling and focusability for TextInput and Button widgets
- updates grid filtering to be case-insensitive
> Use TextInput and Button in Grid

- src/grid/widgets/Grid.ts
**Type:** bug
Add missing height property to custom element.
> Add height CE property to Grid

- package-lock.json
- package.json
Update grund-dojo2 to 4.0.0 so `@keyframes` identifiers do not get minified
> Update grunt-dojo2 to 4.0.0

- src/enhanced-text-input/tests/unit/EnhancedTextInput.ts
- src/text-input/index.ts
- src/text-input/tests/unit/TextInput.ts
Adds `pattern` and `autocomplete` properties and passes them through to the `<input>` node
Resolves #553
> Add pattern and autocomplete properties

- src/grid/tests/unit/widgets/Body.ts
- src/grid/tests/unit/widgets/Cell.ts
- src/grid/tests/unit/widgets/Grid.ts
- src/grid/tests/unit/widgets/Header.ts
- src/grid/tests/unit/widgets/Row.ts
- src/grid/widgets/Body.ts
- src/grid/widgets/Cell.ts
- src/grid/widgets/Grid.ts
- src/grid/widgets/Header.ts
- src/grid/widgets/Row.ts
**Type:** bug
Pass `theme` property to all child widgets.
> Grid propagate theme down to all child widgets

- src/grid/tests/unit/widgets/Grid.ts
- src/grid/tests/unit/widgets/Header.ts
- src/grid/widgets/Grid.ts
- src/grid/widgets/Header.ts
Adds an optional API for custom grid renderers. Implements a `sortRenderer` that can be used to customise the sort button to display when a column is sorted.
Example:
```ts
function sortRenderer(column: ColumnConfig, ascending: boolean, sorter: () => void) {
return v('button', { onclick: sorter }, [ `sort - ${ascending ? 'asc' : 'desc'}` ]);
}
```
Resolves #625
> Custom Sort Renderer

- src/tab/index.ts
- src/tab/tests/unit/Tab.ts
**Type:** bug
When used as a custom element, the `display` of the wrapping placeholder node is set to the same `display` as the root element of the Dojo widget, defaulting to `block`. Because the `Tab` widget sets the root node to be `display: none` it means that the placeholder node picks this up and none of the content is visible. Adding an extra node means that the CE will be picked up as `display: block` and then the inner node is conditionally set to `display: none` depending on the whether a tab is active.
> Add wrapping node so that the widget is not set as display none when used as a CE

- src/grid/tests/unit/widgets/Grid.ts
- src/grid/widgets/Grid.ts
**Type:** bug
Subscribe to the store using the custom `storeId` when passed.
Resolves #639
> Ensure that the store id as the path to subscribe to changes

- src/grid/README.md
- src/grid/tests/unit/widgets/Header.ts
- src/grid/widgets/Header.ts
**Type:** bug
Pass direction rather than a boolean for sort direction, undefined means unsorted.
Resolves #648
> Pass direction to custom sorter

- src/grid/README.md
- src/grid/tests/unit/widgets/Grid.ts
- src/grid/tests/unit/widgets/Header.ts
- src/grid/widgets/Grid.ts
- src/grid/widgets/Header.ts
Implements a custom `filterRenderer` that can be used to customise the filter input to display for filterable columns.
> Custom Filter Renderer

- src/enhanced-text-input/index.ts
- src/enhanced-text-input/tests/unit/EnhancedTextInput.ts
- src/text-input/index.ts
- src/text-input/tests/unit/TextInput.ts
- src/theme/enhanced-text-input.m.css
- src/theme/enhanced-text-input.m.css.d.ts
- src/theme/text-input.m.css
- src/theme/text-input.m.css.d.ts
This fixes an oversight where `helperText` does not render properly on the next line for the Enhanced Text Input widget. It also prevents validation from running and showing errors until the field actually has some kind of value.
> Fix helperText on Enhanced Text Input

- src/listbox/example/index.ts
- src/listbox/index.ts
- src/listbox/tests/functional/Listbox.ts
- src/listbox/tests/unit/Listbox.ts
- src/select/index.ts
- src/select/tests/unit/Select.ts
* Fix listbox and select initial value behavior
* Fix native select behavior with simple options
**Type:** bug
There were a couple of related issues causing the behavior described in 659 and 656. The select widget was passing `''` as the value for `option` elements when there was no value, resulting in empty `value` attributes after some related vdom fixes. It was also not properly treating the option text as the value when no value was specified. This resulted in `onChange` never being called and selections not being persisted for the native select.
Additionally, the select was not passing in the appropriate `activeIndex` to the listbox in the custom select scenario, so an initial selected value would be selected but not …
> Listbox and select fixes

- src/split-pane/example/index.ts
- src/split-pane/index.ts
- src/split-pane/tests/unit/SplitPane.ts
**Type:** bug
Changes global resize observer to resizeObserver. Tidies up some implementation.
- No longer defaults to min collapsewidth of 600
Resolves #665
> Use resize observer in split pane

- package-lock.json
- src/text-input/index.ts
**Type:** bug
This PR uses the `diffProperty` `reference` function to ensure that the `TextInput` re-renders when a new `leading` / `trailing` render function is passed.
This will cause the widget to re-render if the user passes a new `leading` / `trailing` function but will have the side effect that it will also re-render whenever the parent re-renders if the user is using an arrow function or a bind within their renderers.
The most efficient way to use these functions is with named functions / widget-level functions (making use of the autobind functionality).
`w('TextInput', { leading: this.renderLeading }`
or in the case of a changing leading render:
`w('TextInput', { leading: this.toggle ? this.renderA : this.renderZ }` …
> use reference diffProperty

- src/accordion-pane/index.ts
- src/button/index.ts
- src/calendar/CalendarCell.ts
- src/calendar/DatePicker.ts
- src/calendar/index.ts
- src/checkbox/index.ts
- src/combobox/index.ts
- src/dialog/index.ts
- src/icon/index.ts
- src/label/index.ts
- src/listbox/ListboxOption.ts
- src/listbox/index.ts
- src/progress/index.ts
- src/radio/index.ts
- src/range-slider/index.ts
- src/select/index.ts
- src/slide-pane/index.ts
- src/slider/index.ts
- src/split-pane/index.ts
- src/tab-controller/index.ts
- src/tab/index.ts
- src/text-area/index.ts
- src/text-input/index.ts
- src/time-picker/index.ts
- src/title-pane/index.ts
- src/toolbar/index.ts
- src/tooltip/index.ts
Remove bases with generic typings from widgets.
This is part of a move towards encouraging extension via properties instead of class extension. The abstraction involved with having `protected` functions internally and ensuring we don't break those api's is hard to manage and this is not the way we wish to support people using and customising our widgets etc.
Resolves #684
> Export classes rather than bases

- src/dialog/index.ts
- src/dialog/tests/unit/Dialog.ts
- src/theme/dialog.m.css
- src/theme/dialog.m.css.d.ts
Adds themeable open class to dialog.
Enables use of actual material theme in future.
Resolves #690
> add open class to open dialog

- package-lock.json
- src/calendar/CalendarCell.ts
- src/calendar/DatePicker.ts
- src/calendar/date-utils.ts
- src/calendar/example/index.ts
- src/calendar/index.ts
- src/calendar/tests/functional/Calendar.ts
- src/calendar/tests/unit/Calendar.ts
- src/calendar/tests/unit/CalendarCell.ts
- src/calendar/tests/unit/DatePicker.ts
- src/calendar/tests/unit/date-utils.ts
- src/theme/calendar.m.css
- src/theme/calendar.m.css.d.ts
**Type:** Feature
**Description:** This PR adds `minDate`/`maxDate` properties to the `DatePicker` and `Calendar` widgets. It also modifies the `CalendarCell` widget to separate disabled cells from the `currentMonth` indicator.
The previous/next month buttons are disabled if the next month is outside the min/max. The radio buttons on the month/date select windows are disabled if the month is outside the min/max but the links are not removed (though they don't work). Currently there is not separate styling for disabled vs other-month cells.
Resolves #538
> add calendar min max properties

- src/slide-pane/index.ts
- src/slide-pane/tests/unit/SlidePane.ts
**Type:** bug
This refactors the slide-pane to avoid a bug that was showing up (accurately) in our functional tests. I narrowed down the issue to some extra complexity in the transform implementation. The refactor includes the following changes:
- Only calculate transform styles one way
- Perform open/close change checking in a diff property rather than in the renderer
- Use a local state to define whether it is sliding in or out (still gets cleared on next render)
- Remove onAttach hook/state that hasn't been needed since a previous change which removed dom manipulation
Resolves #689
> refactor slide-pane

- src/select/example/index.ts
- src/select/index.ts
- src/select/tests/unit/Select.ts
- src/text-area/example/index.ts
- src/theme/text-input.m.css
- src/theme/text-input.m.css.d.ts
- Adds `helperText` property to `Select`
- Removes `labelAfter` as not compatible with `helperText`
Part of: https://github.com/dojo/widgets/issues/677
> Add helpertext to select

- src/common/example/example.css
- src/theme/toolbar.m.css
- src/theme/toolbar.m.css.d.ts
- src/toolbar/index.ts
- src/toolbar/tests/unit/Toolbar.ts
Toolbar: add CSS classes and rules to lay out children using `flex-direction: row` for the toolbar and `flex-direction: column` for the slide pane.
Resolves #670
> 670 - Toolbar children: set horizontal and vertical layout

- src/calendar/README.md
Adds documentation of the available themed classes in calendar widget.
Resolves #692
> add theme documentation to calendar readme

- src/toolbar/index.ts
- src/toolbar/tests/unit/Toolbar.ts
**Description:** adds an option `align` that is passed to the SlidePane to enable the developer to control the position of the SlidePane
Resolves #671
> Toolbar: add 'align' option for the SlidePane

- package-lock.json
- src/combobox/index.ts
- src/combobox/tests/functional/ComboBox.ts
- src/combobox/tests/unit/ComboBox.ts
- src/common/tests/support/test-helpers.ts
- src/listbox/index.ts
- src/listbox/tests/unit/Listbox.ts
- src/text-input/index.ts
- src/text-input/tests/unit/TextInput.ts
- src/theme/text-input.m.css.d.ts
Hey, remember me? 😉
I've been working on combobox accessibility, so I updated the combo widget with a few things that should make it play nice with more screen reader/browser pairings.
Improves semantics surfaced by screen readers, particularly when using form navigation shortcuts and in announcing combobox role and expanded/collapsed state when landing on the input. The changes include:
- Using `role="presentation"` on intermediary divs to establish a direct relationship between the combobox and the input
- Remove `aria-controls` as it isn't well used or supported, and the functionality it provides would not be desired in this case, as focus should remain on the input
- Make the clear/trigger buttons hidden …
> Update combo a11y

- README.md
- package-lock.json
- package.json
**Description:** Widget example app had no included way to host the project locally. Instead the project asked developers to load the `_build/common/example/index.html` file in the web browser. This caused the widget examples to not load icons on firefox due to CORs issues as the request is not over http.
Resolves #718
> Added command to host widget examples locally

- src/common/example/example.css
- src/common/example/index.ts
- src/common/tests/functional/all.ts
- src/common/tests/unit/all.ts
- src/raised-button/README.md
- src/raised-button/example/index.tsx
- src/raised-button/index.tsx
- src/raised-button/tests/functional/RaisedButton.ts
- src/raised-button/tests/unit/RaisedButton.tsx
- src/theme/raised-button.m.css
- src/theme/raised-button.m.css.d.ts
Adds a RaisedButton that extends the current Button widget by adding an additional class for theming.
Resolves #715
> Add raised button

- src/combobox/example/index.ts
- src/combobox/index.ts
- src/combobox/tests/unit/ComboBox.ts
- src/text-input/index.ts
- src/theme/combobox.m.css
- src/time-picker/index.ts
- src/time-picker/tests/unit/TimePicker.ts
**Description:** 
- Adds helpertext to combobox widget
- Adds onValidate property to the combobox widget
- Updates valid property to use most recent type interface `{valid: boolean, message: string}` instead of a boolean.
Contributes to #677
> [ISSUE-677] Helpertext on combobox

- README.md
- package-lock.json
- package.json
- src/calendar/tests/functional/Calendar.ts
- src/common/example/index.html
- src/common/example/index.ts
- src/time-picker/tests/functional/TimePicker.ts
**Type:** Feature
Dojo widgets in this repo should be compatible with the dojo theme at https://github.com/dojo/themes/. However in the dev environment there was no easy way to test this. This PR adds the ability to test compatibility with the dojo theme easily by toggling radio buttons at the top of the page. Two themes are included:
- dojo
- vanilla (no styling)
Resolves #739 
**Screenshot:**
> Added dojo theme option for examples

- src/time-picker/tests/functional/TimePicker.ts
**Type:** But
The pipeline was having the following error:
```
× chrome 75.0.3770.90 on Linux - TimePicker - disabled menu items cannot be clicked (1.869s)
AssertionError: expected false to be true
at Command.<anonymous>  <src/time-picker/tests/functional/TimePicker.ts:141:12>
at runCallback  <node_modules/src/Command.ts:578:36>
at Command.<anonymous>  <node_modules/src/Command.ts:603:20>
at <node_modules/@theintern/common/index.js:16:7182>
at process._tickDomainCallback  <internal/process/next_tick.js:135:7>
at Command.then  <node_modules/src/Command.ts:599:12>
at Test.disabled menu items cannot be clicked [as test]  <src/time-picker/tests/functional/TimePicker.ts:140:5>
at <src/lib/Test.ts:263:52>
at <node_modules/@theintern/common/index.js:16:7182>
at process._tickDomainCallback …
```
> Fix broken timepicker test

- src/listbox/ListboxOption.ts
- src/listbox/tests/unit/ListboxOption.ts
- src/time-picker/example/index.ts
- src/time-picker/tests/functional/TimePicker.ts
**Type:** Bug
This PR resolves two bugs:
- When the height property is set on the ListboxOption widget (on the .option class in listbox.m.css) this causes the onclick event to stop working in IE 11.
- In the example of the timePicker widget, the drop down will not close if option is selected with your cursor.
Resolves #750
Resolves #704
> Changed onclick to onmousedown on listboxoption

- src/common/example/index.ts
**Type:** bug
Setting the watched property every time causes the examples to infinitely re-render. Only update the module when it is different.
> Only set the watched property when it has changed

- src/card/index.tsx
- src/snackbar/index.tsx
**Type:** bug
Add `this.theme` to all css classes in `Card` and `Snackbar` widgets so they can actually be themed.
> Make card and snackbar themable

- src/button/README.md
- src/checkbox/README.md
- src/radio/README.md
- src/text-area/README.md
**Type:** bug
Updating old examples that show setting the ARIA `describedBy` with just a `describedBy` property, which is gone now. The new way is to set the `aria` property like `aria: { describedBy: 'instructions' }`.
Resolves #775
> Updating old ARIA describedBy examples

- src/text-input/index.ts
This add's `date` as a `type` option on the text-input widget allowing it to use the native date picker.
> Add date type to text-input

- package-lock.json
- src/text-area/example/index.ts
- src/text-area/index.ts
- src/text-area/tests/functional/Textarea.ts
- src/text-area/tests/unit/Textarea.tsx
Add basic validation to the textarea widget, along with an `onValidate` event to match `TextInput`.
**Use case**: checking the validity of a whole form. Currently validation logic for textarea needs to be written each time the widget is used (or a wrapper widget needs to be written).
> Add basic textarea validation and pass valid to helper text

- src/text-area/index.ts
- src/text-area/tests/unit/Textarea.tsx
- src/text-input/index.ts
- src/text-input/tests/unit/TextInput.tsx
**Type:** bug
`onValidate` was being called on every render and thus causing an infinite loop.
This changes it to be conditionally called when the validity or message changes only.
> Fix text-input and text-area validity loop

- package-lock.json
- package.json
- src/examples/src/glob-examples.block.ts
- src/examples/src/properties.block.ts
- src/examples/src/readme.block.ts
- src/examples/src/theme.block.ts
**Type:** bug
Cannot build examples/docs on windows due to the difference in path separators. Switching to use `canonical-path` over `path` resolves this issue.
> Fix examples/docs build on windows

- README.md
- package.json
**Type:** Update
Updated readme to let users know they should not install dependencies in the `src/examples` project. I also removed the blurb about functional tests and the `serve` dependency in `package.json`
> Updated readme, removed serve dependency

- src/text-input/index.ts
As per previous discussion re. splitting out the base input properties.
This provides a base set of properties that `Email` / `Number` input and friends can use consistently.
Sets base properties to:
- aria
- autocomplete
- disabled
- helperText
- label
- labelHidden
- leading
- name
- onBlur
- onClick
- onFocus
- onKeyDown
- onKeyUp
- onOut
- onOver
- onValidate
- onValue
- placeholder
- readOnly
- required
- trailing
- value
- widgetId
Issue: https://github.com/dojo/widgets/issues/844
> Initial separation of base input properties

- src/calendar/index.ts
**Type:** bug
Replaces the `for in` loop with a `map`
Resolves #862
> Fix extra rendered calendar header cells in IE 

- README.md
- src/examples/src/config.ts
**Type:** bug 
Previous naming of `NumberInput` config entry in the example app broke our doc generation.
The standard is to use hyphenated naming as per the folder name / css file name.
> Rename numberInput config entry

- package-lock.json
- package.json
- src/examples/package-lock.json
- src/examples/package.json
- src/examples/src/App.tsx
- src/examples/src/ThemeTable.tsx
- src/examples/src/theme.block.ts
Adds support for comments in the theme css, which will show up in the theme table in the example docs. Only format it supports is as follows:
```css
/* some comment about foo */
.foo {
}
```
> Add comment support for themed css documentation in examples

- src/calendar/CalendarCell.ts
- src/calendar/DatePicker.ts
- src/checkbox/index.ts
- src/checkbox/tests/unit/Checkbox.ts
- src/combobox/index.ts
- src/combobox/tests/unit/ComboBox.ts
- src/dialog/example/index.ts
- src/dialog/index.ts
- src/dialog/tests/unit/Dialog.ts
- src/listbox/index.ts
- src/listbox/tests/unit/Listbox.ts
- src/meta/Focus.ts
- src/radio/index.ts
- src/radio/tests/unit/Radio.ts
- src/range-slider/index.ts
- src/range-slider/tests/unit/RangeSlider.ts
- src/select/index.ts
- src/select/tests/unit/Select.ts
- src/slider/index.ts
- src/slider/tests/unit/Slider.ts
- src/text-area/index.ts
- src/text-area/tests/unit/TextArea.tsx
- src/text-input/index.ts
- src/text-input/tests/unit/TextInput.tsx
- src/time-picker/index.ts
- src/time-picker/tests/unit/TimePicker.ts
**Type:** bug
Creates local focus meta copy that only invalidates the calling widget when the node it is interested in gains / loses focus.
Resolves https://github.com/dojo/framework/issues/569
> framework #569: Focus meta invalidation change

- src/examples/src/App.tsx
**Type:** bug
Removing the text and outlet from the landing page until someone comes up with an actual useful thing to present there
> Remove the widget examples! text from the landing page

- src/examples/src/config.ts
**Type:** bug
Fixes the path/name to the RestfulGrid example.
> Correct the example code fo RestfulGrid to reference the correct file

- src/examples/src/theme.block.ts
Adds support for multiple theme css files in the documentation, for the widget variant scenario.
before: https://dojowidgets-20igmn3ra.now.sh/#widget/number-input/basic
after: https://dojowidgets-8t7a3tgnp.now.sh/#widget/number-input/basic
> Support multiple theme css files in the example documentation

- src/calendar/index.ts
- src/calendar/tests/unit/Calendar.spec.ts
- src/examples/src/config.ts
- src/examples/src/widgets/calendar/Basic.tsx
- src/examples/src/widgets/calendar/CustomFirstWeekDay.tsx
Adds support for customising the first day of the week in the calendar via a property, defaulting to the current fixed first day (sunday)
Resolves #561
> Support customizing the first day of calendar week

- src/chip/index.tsx
- src/chip/tests/Chip.spec.tsx
- src/theme/chip.m.css
- src/theme/chip.m.css.d.ts
Adds an additional icon wrapper element and class to enable a proper material theme to be created for the chip. Also changes `closeIcon` to `closeIconWrapper` to be more accurate and consistent.
> Add iconWrapper element/class to chip

- src/middleware/tests/theme.spec.tsx
- src/middleware/theme.ts
**Type:** bug
Adds `prefix` and fixes issue related to `theme.compose` when used with `classes`.
Resolves #904 
Resolves #905
> Add theme prefix and fix classes clash

- .dojorc
- package-lock.json
- package.json
- src/examples/intern.json
- src/examples/package.json
- src/examples/src/App.tsx
- src/examples/src/Example.m.css
- src/examples/src/Example.m.css.d.ts
- src/examples/src/Example.tsx
- src/examples/src/Landing.tsx
- src/examples/src/Menu.tsx
- src/examples/src/main.tsx
- src/examples/src/routes.tsx
- src/examples/src/tests.tsx
- src/main.tsx
Adds support for running tests in browser as part of the example runner. An extra Tests tab is added to each widget example, which runs it's own suite. This means you can dev and test in the example runner with a single command.
Needs some updates from webpack-contrib/cli-build-app
> Support running tests in the example runner

- .dojorc
- src/examples/intern/intern.json
- src/examples/intern/reporter.js
In lieu of writing an actual new reporter (which we will do in the future), for now just override some existing css styles in the intern reporter.
* removes header to give more screen estate
* removes summary to give more screen estate
* expands all suites always
* hides expands/collapse controls as broken with the above
* make the column info be like a `pre` element
> Hack some styles in to the existing intern html reporter

- src/constrained-input/tests/unit/ConstrainedInput.spec.tsx
There is an issue running the constrained input tests on the site because of some inconsistencies with i18n. I'm removing i18n from the equation by always mocking the validation middleware since its not really important for these tests.
> Removing i18n from constrained input tests

- src/calendar/tests/unit/date-utils.spec.ts
* NA Any widget variant uses `theme.compose` like [this](https://github.com/dojo/widgets/issues/847)
* NA WidgetProperties are exported
The calendar date util tests for `monthInMin` were failing as they were using the Date constructor to parse strings which proved inconsistent and caused tests to fail in some timezones. This switches the tests to using individual date and time component values instead https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
Resolves: #919
> Fixes calendar date util test error

- src/icon/tests/unit/Icon.spec.ts
**Type:** bug
The icon test was accidentally removed when converting tests to `.spec` files, this adds them back.
> Add missing icon test back

- package-lock.json
- src/common/tests/support/test-helpers.ts
- src/constrained-input/tests/unit/ConstrainedInput.spec.tsx
- src/email-input/tests/EmailInput.spec.tsx
- src/menu/tests/Menu.spec.tsx
- src/middleware/tests/theme.spec.tsx
- src/middleware/theme.ts
- src/number-input/tests/unit/NumberInput.spec.tsx
- src/outlined-button/tests/unit/OutlinedButton.spec.tsx
- src/raised-button/tests/unit/RaisedButton.spec.tsx
- src/theme/button.m.css
- src/theme/constrained-input.m.css
- src/theme/email-input.m.css
- src/theme/menu.m.css
- src/theme/number-input.m.css
- src/theme/outlined-button.m.css
- src/theme/raised-button.m.css
- src/theme/raised-button.m.css.d.ts
Amends the `theme.compose` code to use the base-variant css if the base component is not themed.
The effect of this is that the base-theme for the variant will be used so that widgets such as `outline-button` can have an appropriate base theme.
**impacts of this change:**
- all widgets that use `theme.compose` will have to manually use `composes` within their base-theme css on classes they wish to be themeable but to use the base-component's css.
ie. 
```css
/* outline-button.m.css */
.root {
composes: root from './button.m.css';
border: 1px solid black;
}
```
- In the above, outline-button case, if a dojo / material etc theme is created and applied via a theme injector for `button`, but not …
> Theme compose reloaded

- src/examples/src/config.ts
- src/examples/src/widgets/raised-button/DisabledSubmit.tsx
- src/examples/src/widgets/raised-button/ToggleButton.tsx
Adds additional examples for the raised button, matching other button widgets
Related to #876
> add examples for raised button

- src/combobox/index.tsx
- src/combobox/tests/unit/ComboBox.spec.tsx
- src/helper-text/index.tsx
- src/select/index.tsx
- src/select/tests/unit/Select.spec.tsx
- src/text-area/index.tsx
- src/text-area/tests/unit/TextArea.spec.tsx
- src/text-input/index.tsx
- src/text-input/tests/unit/TextInput.spec.tsx
Passes down `theme` and `classes` in the `TextArea`, `TextInput`, `ComboBox`, `Select` widgets.
Resolves #926
> Pass theme and classes down to HelperText for TextArea, TextInput, ComboBox, Select

- src/calendar/date-utils.tsx
- src/calendar/index.tsx
- src/calendar/tests/unit/Calendar.spec.tsx
- src/calendar/tests/unit/date-utils.spec.tsx
**Type:** bug
Updated the Calendar to only take the year, month, and day portions of a date when determining if a day is outside of the min/max dates. Previously it was possible to set a min / max date with a time that would place a day outside of a given range; e.g. if `{ minDate: new Date() }` was used the current day would be outside of the minDate range.
Resolves #857
> ignore time when checking min and max dates

- src/calendar/CalendarCell.tsx
- src/calendar/DatePicker.tsx
- src/checkbox/index.tsx
- src/chip/index.tsx
- src/combobox/index.tsx
- src/global-event/index.tsx
- src/grid/Body.tsx
- src/grid/Cell.tsx
- src/grid/Footer.tsx
- src/grid/Header.tsx
- src/grid/Row.tsx
- src/helper-text/index.tsx
- src/label/index.tsx
- src/listbox/ListboxOption.tsx
- src/listbox/index.tsx
- src/menu/ListBoxItem.tsx
- src/menu/MenuItem.tsx
- src/popup/index.tsx
- src/radio/index.tsx
- src/range-slider/index.tsx
- src/select/index.tsx
- src/slider/index.tsx
- src/snackbar/index.tsx
- src/split-pane/index.tsx
- src/tab-controller/TabButton.tsx
- src/tab/index.tsx
- src/text-area/index.tsx
- src/text-input/index.tsx
- src/time-picker/index.tsx
- src/toolbar/index.tsx
Adds missing descriptions for all widget properties
Resolves #812
> Added descriptions for all widget properties

- .dojorc
- package-lock.json
- src/examples/src/config.tsx
- src/examples/src/widgets/password-input/Basic.tsx
- src/password-input/README.md
- src/password-input/index.tsx
- src/password-input/tests/unit/password-input.spec.tsx
- src/theme/default/index.ts
- src/theme/default/password-input.m.css
- src/theme/default/password-input.m.css.d.ts
- src/theme/dojo/index.ts
- src/theme/dojo/password-input.m.css
- src/theme/dojo/password-input.m.css.d.ts
- src/theme/dojo/widgets.css
Adding password input widget, `PasswordInput`.  Is a regular `ConstrainedInput` widget but with a set type of `password` and a toggle button to see the password.
Resolves #792
> Adding PasswordInput widget

- package-lock.json
- src/examples/src/config.tsx
- src/examples/src/widgets/grid/ColumnResize.tsx
- src/examples/src/widgets/grid/Filtering.tsx
- src/examples/src/widgets/grid/data.tsx
- src/grid/Body.tsx
- src/grid/Cell.tsx
- src/grid/Header.tsx
- src/grid/Row.tsx
- src/grid/index.tsx
- src/grid/interfaces.d.ts
- src/grid/styles/header.m.css
- src/grid/styles/header.m.css.d.ts
- src/grid/tests/unit/Body.spec.tsx
- src/grid/tests/unit/Cell.spec.tsx
- src/grid/tests/unit/Grid.spec.tsx
- src/grid/tests/unit/Header.spec.tsx
- src/grid/tests/unit/Row.spec.tsx
- src/theme/default/grid-header.m.css
- src/theme/dojo/grid-cell.m.css
- src/theme/dojo/grid-header.m.css
Adds support for resizable grid columns via a new optional property in `ColumnConfig`. Setting column as `resizable` will enable the column to be resized via clicking the right side column border and dragging left or right.
```ts
const columnConfig = [
{
id: 'id',
title: 'Id',
resizable: true
},
{
id: 'name',
title: 'Name'
},
{
id: 'id',
title: 'Id',
resizable: true
}
];
```
**Note:** The column widths are not persistent across instances of the grid and cannot be set externally to the grid.
Resolves #935
> Resizable Grid Columns

- src/grid/styles/paginated-footer.m.css
- src/theme/dojo/grid-paginated-footer.m.css
**Type:** bug
Tweak the pagination styling
> Tweak pagination styles

- package-lock.json
- package.json
- src/examples/src/config.tsx
Upgrades parade to 0.0.5, which now supports theme selection.
> Upgrade parade to support selecting theme

- src/examples/src/widgets/grid/Paginated.tsx
- src/grid/PaginatedBody.tsx
- src/grid/PaginatedFooter.tsx
- src/grid/tests/unit/PaginatedBody.spec.tsx
- src/grid/tests/unit/PaginatedFooter.spec.tsx
**Type:** bug
Fixes issues with rendering the grid and pagination controls with a limited dataset.
Resolves #968
> Fix issues with pagination on small data sets

- src/examples/src/config.tsx
- src/examples/src/widgets/progress/ProgressWithChangingValues.tsx
- src/examples/src/widgets/progress/ProgressWithCustomOutput.tsx
- src/examples/src/widgets/progress/ProgressWithMax.tsx
- src/examples/src/widgets/progress/ProgressWithoutOutput.tsx
**Description:** Moved progress bar examples to new format and structure
Resolves #825
> move progress bar examples

- .dojorc
- package-lock.json
- package.json
* Updates to the latest cli-test-intern, tests should start passing
* Uses cli-build-widget to build the default theme over cli-build-theme
> Update cli-test-intern and build default theme with build-widget command

- src/common/styles/variables.css.d.ts
- src/theme/default/variables.css.d.ts
- src/theme/dojo/index.ts
- src/theme/dojo/listbox-item.m.css
- src/theme/dojo/listbox-item.m.css.d.ts
- src/theme/dojo/menu-item.m.css
- src/theme/dojo/menu-item.m.css.d.ts
- src/theme/dojo/menu.m.css
- src/theme/dojo/menu.m.css.d.ts
- src/theme/dojo/variables.css.d.ts
- src/theme/material/variables.css.d.ts
Adds Dojo themeing for the Menu, MenuItem and ListboxItem widgets. This ticks off these widgets for #952 
MenuItem:
ListboxItem:
> Dojo Theme for Menu, MenuItem and ListboxItem

- src/theme/default/button.m.css
- src/theme/default/button.m.css.d.ts
- src/theme/dojo/button.m.css
- src/theme/dojo/button.m.css.d.ts
- src/theme/dojo/index.ts
- src/theme/dojo/outlined-button.m.css
- src/theme/dojo/outlined-button.m.css.d.ts
This PR adds the Dojo theme for the OutlinedButton widget. It ticks a box for #952 which aims to add a Dojo theme for all the widgets.
> Dojo Theme for OutlinedButton

- src/theme/dojo/checkbox-group.m.css
- src/theme/dojo/checkbox-group.m.css.d.ts
- src/theme/dojo/index.ts
This PR adds the Dojo themining for the CheckboxGroup widget (tickbox of #952) . The styling is fairly minimal as the widget is a container for Checkboxs which are already styled.
> Dojo Theme for Checkbox Group

- src/common/styles/variables.css.d.ts
- src/examples/src/config.tsx
- src/examples/src/widgets/menu/Basic.tsx
- src/examples/src/widgets/menu/Controlled.tsx
- src/examples/src/widgets/menu/ItemRenderer.tsx
- src/examples/src/widgets/menu/LargeOptionSet.tsx
- src/examples/src/widgets/menu/ListBox.tsx
- src/examples/src/widgets/popup/MenuPopup.tsx
- src/examples/src/widgets/progress/ProgressWithChangingValues.tsx
- src/menu/ListBoxItem.tsx
- src/menu/MenuItem.tsx
- src/menu/index.tsx
- src/menu/menu.m.css
- src/menu/menu.m.css.d.ts
- src/menu/tests/ListBoxItem.spec.tsx
- src/menu/tests/Menu.spec.tsx
- src/menu/tests/MenuItem.spec.tsx
- src/select/index.tsx
- src/select/tests/Select.spec.tsx
- src/theme/default/variables.css.d.ts
- src/theme/dojo/variables.css.d.ts
- src/theme/material/variables.css.d.ts
- Adds scrolling virtual window
- adds required `total` property required
- This will be used for future enhancements around pagination
Resolves #983
> Add Virtual scrolling / rendering to the Menu

- src/examples/src/config.tsx
- src/examples/src/widgets/menu/Dividers.tsx
- src/menu/index.tsx
- src/menu/tests/Menu.spec.tsx
- src/theme/default/menu.m.css
- src/theme/default/menu.m.css.d.ts
Adds a `divider` property to menu items that renders an `hr` element after the item if true.
Resolves #939
> Menu dividers

- src/examples/src/config.tsx
- src/form/middleware.ts
- src/form/tests/unit/FormMiddleware.spec.tsx
**Type:** bug
Follow up to #807 
- Update form middleware unit tests to directly test the middleware.
- Properly reset form and field disabled values.
- Properly consider a form with required fields invalid before any values are set.
- Add form to examples config (missed this in prior PR).
> Form middleware - Tests and bug fixes

- src/theme/material/index.ts
**Type:** bug
I missed this when adding the material theme for chips
> Add chip to material theme

- src/theme/default/menu.m.css
- src/theme/dojo/menu.m.css
**Type:** bug
In the select widget update the background color for the select widget was lost. This PR adds in  the default background color the was previously used in widget version 6 before the update: https://github.com/dojo/widgets/blob/v6.1.0/src/theme/select.m.css
Resolves #1002
> Added default background color menu widget

- .dojorc
- src/examples/src/config.tsx
- src/examples/src/widgets/radio-group/Basic.tsx
- src/examples/src/widgets/radio-group/CustomLabel.tsx
- src/examples/src/widgets/radio-group/CustomRenderer.tsx
- src/examples/src/widgets/radio-group/InitialValue.tsx
- src/radio-group/README.md
- src/radio-group/index.tsx
- src/radio-group/middleware.ts
- src/radio-group/tests/RadioGroup.spec.tsx
- src/radio-group/tests/middleware.spec.ts
- src/theme/radio-group.m.css
- src/theme/radio-group.m.css.d.ts
This pull request adds a new `RadioGroup` widget and associated middleware.
Resolves #798
> feat: add RadioGroup middleware

- src/chip/tests/Chip.spec.tsx
- src/combobox/tests/unit/ComboBox.spec.tsx
- src/dialog/tests/unit/Dialog.spec.tsx
- src/form/tests/unit/Form.spec.tsx
- src/form/tests/unit/FormMiddleware.spec.tsx
- src/grid/tests/unit/Header.spec.tsx
- src/select/tests/Select.spec.tsx
In Sinon 5, `reset` is deprecated and `resetHistory` is preferred. This PR silences the deprecation warnings whilst testing.
Example warnings:
> Replace reset with resetHistory to remove Sinon deprecation warning

- src/card/index.tsx
- src/card/tests/unit/Card.spec.tsx
Converts the `Card` widget to a functional component
> Convert Card to functional widget

- src/form/index.tsx
**Type:** enhancement
Makes `onSubmit` optional for the form
Resolves #1021
> make onSubmit optional for the form

- src/tooltip/index.tsx
- src/tooltip/tests/unit/Tooltip.spec.tsx
Converts the Tooltip widget to a functional widget along with the unit test. In turn this simplifies the widget slightly.
> Convert Tooltip to functional widget

- src/examples/src/config.tsx
- src/examples/src/widgets/password-input/NoRules.tsx
- src/password-input/index.tsx
- src/password-input/tests/unit/password-input.spec.tsx
- src/theme/dojo/password-input.m.css
**Type:** enhancement
- makes rules optional, renders text-input when no rules present
- handles validation when using only a text-input
- adds tests
- fixes bug where button was submit type so forms would submit
Resolves #1020
> password input - make rules optional, fix submit, add tests

- src/theme/material/dialog.m.css
There was a problem with the dialog exit animation using the material theme. The material theme had a `display: none` on the root of the dialog, so as soon as the dialog would close, the parent would be hidden, and thus the exit animation could never start, and therefore finish. This would leave the vdom in a weird state in that it was keeping the old nodes around waiting for the animation to finish.
> Fixing material dialog animation

- src/form/index.tsx
- src/form/middleware.ts
- src/form/tests/unit/Form.spec.tsx
Allows the form widget to take an action and method to perform a standard web form post.
Resolves #1034
> Pass action and method to form

- .dojorc
- README.md
- src/common/styles/variables.css.d.ts
- src/common/tests/support/test-helpers.ts
- src/examples/src/config.tsx
- src/examples/src/widgets/native-select/Basic.tsx
- src/native-select/README.md
- src/native-select/index.tsx
- src/native-select/tests/NativeSelect.spec.tsx
- src/theme/default/index.ts
- src/theme/default/native-select.m.css
- src/theme/default/native-select.m.css.d.ts
- src/theme/default/variables.css.d.ts
- src/theme/dojo/index.ts
- src/theme/dojo/native-select.m.css
- src/theme/dojo/native-select.m.css.d.ts
- src/theme/dojo/variables.css.d.ts
- src/theme/material/native-select.m.css
- src/theme/material/variables.css.d.ts
- src/theme/material/widgets.css
**Type:** Feature
* [NA] Any widget variant uses `theme.compose` like [this](https://github.com/dojo/widgets/issues/847)
**Description:** 
Added a native select component so users have the option other than our current custom built select.
Resolves #973
> Added native select widget

- src/theme/material/tooltip.m.css
- src/theme/material/tooltip.m.css.d.ts
- src/theme/material/variables.css
Adds basic material theme for the Tooltip widget.
Resolves #1041
> Material theme for tooltip

- src/select/index.tsx
- src/select/tests/Select.spec.tsx
**Type:** Feature
Adds name and value to the trigger button on the select component
Resolves #1045
> Add name and value to trigger button on select component

- src/theme/dojo/calendar.m.css
Enhanced calendar controls by moving them from the sides to the `topMatter`. Centered month/year to allow space for controls.
Old:
New:
New hover/focus:
> Enhanced UX for Calendar controls (Dojo Theme)

- src/date-input/index.tsx
- src/date-input/tests/unit/DateInput.spec.tsx
It looks like text input was merged after a new widget was added, and this new widget used a text input.  This PR is changing `value` of `DateInput` to use `initialValue` instead.
> Fixing issue with date input and new text input changes

- src/text-area/index.tsx
- src/text-area/tests/unit/TextArea.spec.tsx
Converting `TextArea` to a functional widget. Next up is managed `value` support like the recent changes for `TextInput`.
> Adding functional text area

- src/examples/src/widgets/text-area/Basic.tsx
- src/examples/src/widgets/text-area/Disabled.tsx
- src/examples/src/widgets/text-area/HelperText.tsx
- src/examples/src/widgets/text-area/HiddenLabel.tsx
- src/examples/src/widgets/text-area/ValidatedCustom.tsx
- src/examples/src/widgets/text-area/ValidatedRequired.tsx
- src/text-area/index.tsx
- src/text-area/tests/unit/TextArea.spec.tsx
Making `TextArea` use the `initialValue` pattern.
Resolves #1028
> Adding managed text area value

- .travis.yml
**Type:** bug
Do not deploy documentation if build fails.
> Do not deploy if the build fails

- src/card/index.tsx
- src/checkbox-group/index.tsx
- src/checkbox/index.tsx
- src/chip/index.tsx
- src/constrained-input/index.tsx
- src/context-menu/index.tsx
- src/context-popup/index.tsx
- src/date-input/index.tsx
- src/dialog/index.tsx
- src/form/index.tsx
- src/icon/index.tsx
- src/menu/index.tsx
- src/middleware/theme.tsx
- src/native-select/index.tsx
- src/popup/index.tsx
- src/radio-group/index.tsx
- src/select/index.tsx
- src/snackbar/index.tsx
- src/switch/index.tsx
- src/text-area/index.tsx
- src/text-input/index.tsx
- src/tooltip/index.tsx
**Type:** bug
Extend `ThemeProperties` and `FocusProperties` where the respective middleware is used in fucntional widgets.
Resolves #1080
> Add ThemeProperties, FocusProperties to functional widgets using those middleware

- deploy.sh
Fixes deployment issue to now by adding `--confirm` flag.
Related issue: https://github.com/zeit/now/pull/3690
> Add confirm flag to now deployments

- src/examples/src/config.tsx
**Type:** bug
Sandbox medium height of 300px is ~55px short of containing the DateInput with the calendar expanded. Increased the sandbox size to large to prevent unexpected popup placement.
Resolves #1094
> Expanded DateInput example sandbox to large

- src/constrained-input/index.tsx
- src/constrained-input/tests/unit/ConstrainedInput.spec.tsx
Allows constrained input to accept a helper text property which overrides the generated description.
Resolves #1108
> Add helper-text pass through and tests

- src/grid/processes.ts
**Type:** bug
On the first render the `onValue` of the filter textbox is triggered with `""`. This triggered the filter process before the fetch process resolved so the `pageSize` had not been set. Moving the setting of `pageSize` to the `preFetcher` makes it available for the first filter command. 
Resolves #1083
> Set page size on preFetch so it's ready for initial filter

- src/dialog/index.tsx
Uses the body scroll middleware with dialog
Resolves #669
> Stop body scrolling whilst dialog open

- src/date-input/index.tsx
- src/date-input/tests/unit/DateInput.spec.tsx
- src/theme/material/date-input.m.css
- src/theme/material/date-input.m.css.d.ts
- src/theme/material/index.ts
Material theme for DateInput
Resolves #1073
> Material theme for DateInput

- src/grid/Row.tsx
- src/grid/tests/unit/Row.spec.tsx
- src/theme/default/grid-row.m.css
- src/theme/default/grid-row.m.css.d.ts
- src/theme/material/grid-cell.m.css
- src/theme/material/grid-footer.m.css
- src/theme/material/grid-header.m.css
- src/theme/material/grid-header.m.css.d.ts
- src/theme/material/grid-paginated-footer.m.css
- src/theme/material/grid-paginated-footer.m.css.d.ts
- src/theme/material/grid-row.m.css
- src/theme/material/grid-row.m.css.d.ts
- src/theme/material/grid.m.css
- src/theme/material/grid.m.css.d.ts
- src/theme/material/index.ts
- src/theme/material/variables.css
- src/theme/material/widgets.css
Adding some materialesque styles for the grid!  Still might need a little work, but the bulk of it is here.  The only bits that look odd are when filtering is involved, since the material text boxes are so large.
Resolves #1078
> Adding grid material styles

- src/text-input/index.tsx
- src/text-input/tests/unit/TextInput.spec.tsx
Applying the `noLabel` class when the label exists, but is hidden!
Resolves #1115
> Adding no-label class when label is hidden

- src/grid/Header.tsx
- src/grid/tests/unit/Header.spec.tsx
- src/theme/default/grid-header.m.css
- src/theme/default/grid-header.m.css.d.ts
- src/theme/material/grid-header.m.css
- src/theme/material/grid-header.m.css.d.ts
Taming the grid filter styles on the material theme. Had to add some extra classes to `Header` so I could theme them.
Resolves #1117
> Updating grid material filter styles

- src/theme/material/calendar.m.css
- src/theme/material/variables.css
**Type:** bug
Adds missing style variables to calendar widget
Resolves #1113
> Added missing variables in material theme

- src/examples/src/config.tsx
- src/examples/src/widgets/form/ActionForm.tsx
- src/examples/src/widgets/form/Basic.tsx
- src/form/index.tsx
- src/form/tests/unit/Form.spec.tsx
Adds a `name` property to the form.
Resolves #1044
> Add name property to Form

- .dojorc
- src/examples/src/config.tsx
- src/examples/src/widgets/loading-indicator/Basic.tsx
- src/loading-indicator/README.md
- src/loading-indicator/index.tsx
- src/loading-indicator/tests/unit/LoadingIndicator.spec.tsx
- src/theme/default/index.ts
- src/theme/default/loading-indicator.m.css
- src/theme/default/loading-indicator.m.css.d.ts
- src/theme/dojo/index.ts
- src/theme/dojo/loading-indicator.m.css
- src/theme/dojo/loading-indicator.m.css.d.ts
- src/theme/material/index.ts
- src/theme/material/loading-indicator.m.css
- src/theme/material/loading-indicator.m.css.d.ts
This pull request adds an indeterminate loading indicator widget.
Resolves #1119
**Preview**
> feat: loading indicator

- src/avatar/index.tsx
- src/card/index.tsx
- src/checkbox-group/index.tsx
- src/checkbox/index.tsx
- src/chip/index.tsx
- src/context-menu/index.tsx
- src/context-popup/index.tsx
- src/dialog/index.tsx
- src/form/index.tsx
- src/helper-text/index.tsx
- src/icon/index.tsx
- src/menu/index.tsx
- src/native-select/index.tsx
- src/popup/index.tsx
- src/radio-group/index.tsx
- src/select/index.tsx
- src/slider/index.tsx
- src/snackbar/index.tsx
- src/switch/index.tsx
- src/text-area/index.tsx
- src/text-input/index.tsx
- src/tooltip/index.tsx
There does not appear to be difference when we remove the `ThemeMixin` or `FocusedProperties` extends clauses from the functional widgets... I manually verified a few widgets with and without the extends and the results were the same.
As such, I removed all the `ThemeMixin` and `FocusedProperty` extensions from the functional widgets.
> Removing certain functional widget property extends

- .dojorc
- src/examples/src/config.tsx
- src/examples/src/widgets/header-card/ActionCard.tsx
- src/examples/src/widgets/header-card/Basic.tsx
- src/examples/src/widgets/header-card/MediaCard.tsx
- src/header-card/README.md
- src/header-card/index.tsx
- src/header-card/tests/unit/HeaderCard.spec.tsx
- src/theme/default/header-card.m.css
- src/theme/default/header-card.m.css.d.ts
- src/theme/dojo/header-card.m.css
- src/theme/dojo/header-card.m.css.d.ts
- src/theme/dojo/index.ts
- src/theme/material/header-card.m.css
- src/theme/material/header-card.m.css.d.ts
- src/theme/material/index.ts
**Note:** This PR relies on #1105 and #1104 being merged. Please review those first.
This adds a new card, a header card, that wraps the card implementation and takes over rendering of the card's `header` named child to provide a consistently-styled header for the card. The header-card takes all the same properties and children (minus `header` named child). It takes over rendering the `title` and `subtitle` if provided and will render them in the header (and prevent them from being passed to the underlying card). It also adds an `avatar` property which will render an avatar in the header next to the title/subtitle.
Resolves #978 
**Example**
```tsx
<HeaderCard
avatar={() => <Avatar src={avatar} />} …
```
> Add Header Card widget

- src/theme/material/range-slider.m.css
**Type:** bug
Fixes material styling of the`RangeSlider` widget. Adds styling for the missing track and appropriate fill.
Resolves #1144
> Fix material styling of track

- src/checkbox-group/index.tsx
- src/checkbox-group/tests/CheckboxGroup.spec.tsx
- src/examples/src/widgets/checkbox-group/CustomRenderer.tsx
- src/examples/src/widgets/menu/ItemRenderer.tsx
- src/examples/src/widgets/radio-group/CustomRenderer.tsx
- src/examples/src/widgets/select/CustomRenderer.tsx
- src/menu/index.tsx
- src/menu/tests/Menu.spec.tsx
- src/radio-group/index.tsx
- src/radio-group/tests/RadioGroup.spec.tsx
- src/select/index.tsx
- src/select/tests/Select.spec.tsx
Resolves #1150 
Update the `CheckboxGroup`, `RadioGroup`, `Menu`, and `Select` widgets to use child renderer functions instead of relying on `renderer`/`itemRenderer` properties. Other widgets still accept custom renderer properties, but accept multiple properties for rendering different portions of the widget and therefore were left alone.
> Use child renderer functions where possible

- src/examples/src/widgets/header-card/ActionCard.tsx
- src/examples/src/widgets/header-card/Basic.tsx
- src/examples/src/widgets/header-card/MediaCard.tsx
- src/theme/dojo/header-card.m.css
- src/theme/material/header-card.m.css
**Type:** bug
Resolves #1143 
Strip the margin and reset the font weight for the header card's title and subtitle.
> Fix: header card styling

- src/radio/index.tsx
- src/radio/tests/unit/Radio.spec.tsx
**Type:**  feature
Converts `Radio` to a function based widget. 
Resolves #1148
> Refactor radio as functional widget

- src/examples/src/widgets/select/Basic.tsx
- src/select/index.tsx
- src/select/tests/Select.spec.tsx
Updating `Select` to display option label instead of value, if available.
Resolves #1164
> Select displays option label if available (#1164)

- src/examples/src/widgets/range-slider/Basic.tsx
- src/examples/src/widgets/range-slider/Disabled.tsx
- src/examples/src/widgets/range-slider/Events.tsx
- src/examples/src/widgets/range-slider/Labelled.tsx
- src/examples/src/widgets/range-slider/MinMax.tsx
- src/examples/src/widgets/range-slider/Required.tsx
- src/examples/src/widgets/range-slider/Tooltip.tsx
- src/range-slider/index.tsx
- src/range-slider/tests/unit/RangeSlider.spec.tsx
This pull request updates `RangeSlider` to be a functional widget, updates its tests to use assertion templates, and updates its internal logic to use the new `initialValue` pattern.
Resolves #1028
Resolves #1147
**Preview:**
> fix: convert RangeSlider to functional widget

- src/grid/Body.tsx
- src/grid/Header.tsx
- src/grid/PaginatedBody.tsx
- src/grid/PaginatedFooter.tsx
- src/grid/PlaceholderRow.tsx
- src/grid/index.tsx
- src/grid/styles/grid.m.css
- src/grid/styles/header.m.css
- src/grid/styles/header.m.css.d.ts
- src/grid/styles/placeholder-row.m.css
- src/grid/styles/placeholder-row.m.css.d.ts
- src/grid/styles/row.m.css
- src/grid/tests/unit/Body.spec.tsx
- src/grid/tests/unit/Header.spec.tsx
- src/grid/tests/unit/PaginatedBody.spec.tsx
- src/grid/tests/unit/PaginatedFooter.spec.tsx
- src/header-card/index.tsx
- src/theme/default/grid-cell.m.css
- src/theme/default/grid-header.m.css
- src/theme/default/grid-paginated-footer.m.css
- src/theme/default/grid-placeholder-row.m.css
- src/theme/default/grid-row.m.css
- src/theme/dojo/grid-placeholder-row.m.css
- src/theme/material/grid-placeholder-row.m.css
- src/theme/material/grid-placeholder-row.m.css.d.ts
- src/theme/material/grid-row.m.css
- src/theme/material/variables.css
Tweaks to the overall look and feel of the grid in all three themes. Plus using the correct mdc vars for the grid material theme.
Resolves #1184
> Clean up the grid styling across default, dojo and material

- src/tab-controller/TabButton.tsx
- src/tab-controller/index.tsx
- src/tab-controller/tests/unit/TabButton.spec.tsx
- src/tab-controller/tests/unit/TabController.spec.tsx
Addresses a portion of #1171
- Convert `<TabController>` and `<TabButton>` to functional widgets using tsx.
- Convert the associated test files to use tsx.
> Convert `<TabController />` and `<TabButton />` to functional widgets

- src/calendar/CalendarCell.tsx
- src/calendar/DatePicker.tsx
- src/calendar/index.tsx
- src/calendar/tests/unit/Calendar.spec.tsx
- src/calendar/tests/unit/CalendarCell.spec.tsx
- src/calendar/tests/unit/DatePicker.spec.tsx
This is a straight up conversion of the Calendar widget and its child widgets to be functional and use TSX over HyperScript. There is still more work to be done as described in #1112.
The following is covered in this PR from the original ticket:
> Convert Calendar to functional TSX widget

- src/button/index.tsx
- src/examples/src/widgets/grid/CustomFilterRenderer.tsx
- src/grid/Cell.tsx
- src/grid/tests/unit/Cell.spec.tsx
- src/theme/dojo/grid-cell.m.css
- Removing bad `FocusProperties` import
- Removing `ThemedProperties` and `FocusProperties` from button properties
- Fixing `extraClasses` uses of button
Resolves #1197
> A few button fixes (#1197)

- src/middleware/tests/theme.spec.tsx
- src/middleware/theme.tsx
**Type:** bug
Only considers strings to be prefixed if larger than the prefix string length.
Resolves #1206
> Don’t rewrite exact prefix matches

- src/examples/src/widgets/slide-pane/Basic.tsx
- src/examples/src/widgets/slide-pane/BottomAlignSlidePane.tsx
- src/examples/src/widgets/slide-pane/FixedWidthSlidePane.tsx
- src/examples/src/widgets/slide-pane/LeftAlignSlidePane.tsx
- src/examples/src/widgets/slide-pane/RightAlignSlidePane.tsx
- src/examples/src/widgets/slide-pane/UnderlaySlidePane.tsx
- src/slide-pane/index.tsx
- src/slide-pane/tests/unit/SlidePane.spec.tsx
Converting slide pane to a functional widget.
Resolves #1173
> Converting slide pane to a functional widget.

- src/label/index.tsx
- src/label/tests/unit/Label.spec.tsx
Updates the `Label` widget to be function based. Removes extraneous aria properties.
Resolves #1172
> Convert Label wiget to be function based

- src/accordion-pane/index.tsx
- src/accordion-pane/tests/unit/AccordionPane.spec.tsx
- src/examples/src/widgets/accordion-pane/Basic.tsx
- src/examples/src/widgets/accordion-pane/Exclusive.tsx
- src/examples/src/widgets/title-pane/Basic.tsx
- src/examples/src/widgets/title-pane/HeadingLevel.tsx
- src/examples/src/widgets/title-pane/NonCloseable.tsx
- src/header/index.tsx
- src/theme/default/accordion-pane.m.css
- src/theme/default/accordion-pane.m.css.d.ts
- src/theme/material/accordion-pane.m.css
- src/title-pane/index.tsx
- src/title-pane/tests/unit/TitlePane.spec.tsx
This pull request updates `TitlePane` to be a functional widget, updates its tests to use assertion templates, and updates its internal logic to use the new `initialValue` pattern.
Resolves #1167
**Preview:**
> feat: functional TitlePane and AccordionPane

- src/theme/default/time-picker.m.css
- src/theme/default/time-picker.m.css.d.ts
- src/theme/dojo/time-picker.m.css
- src/time-picker/index.tsx
- src/time-picker/tests/unit/TimePicker.spec.tsx
Moves the styles for the embedded `TimePicker` to the prefix `input`.
References #1038
> Move TimePicker to theme.compose

- src/date-input/index.tsx
- src/date-input/tests/unit/DateInput.spec.tsx
- src/theme/default/date-input.m.css
- src/theme/default/date-input.m.css.d.ts
- src/theme/dojo/date-input.m.css
Moves the styles for the embedded `TextInput` to the prefix `input`.
References #1038
> Move DateInput to theme.compose

- src/password-input/index.tsx
- src/password-input/tests/unit/password-input.spec.tsx
- src/theme/default/index.ts
- src/theme/default/password-input.m.css
- src/theme/default/password-input.m.css.d.ts
- src/theme/dojo/breadcrumb-group.m.css.d.ts
- src/theme/dojo/password-input.m.css
- src/theme/dojo/password-input.m.css.d.ts
- src/theme/material/breadcrumb-group.m.css.d.ts
Moves the styles for the embedded `PasswordInput` to the prefix `toggleButton`.
References #1038
> Move PasswordInput to theme.compose

- src/examples/src/config.tsx
- src/examples/src/widgets/global-event/Basic.tsx
Adds a basic example of using the `GlobalEvent` widget to add a keyup listener.
Resolves #822
> Add basic GlobalEvent example

- .github/workflows/ci.yml
> Use npm install instead of npm ci

- package-lock.json
- src/calendar/DatePicker.tsx
- src/calendar/index.tsx
- src/calendar/tests/unit/Calendar.spec.tsx
This is part of the ongoing Calendar refactor described in #1112 and replaces render properties with optional named render children functions.
**Interface**
```tsx
export interface CalendarChildren {
/** Format the displayed current month and year */
monthLabel?: (month: number, year: number) => RenderResult;
/** Format the weekday column headers */
weekdayCell?: (day: { short: string; long: string }) => RenderResult;
}
```
**Usage**
```tsx
<Calendar>
{{
monthLabel: (month) => <span>{month}</span>,
weekdayCell: (day) => <span>{day.long}</span>
}}
</Calendar>
```
Resolves: #1221
> Accept child renderers for month / weekday cell instead of properties

- src/global-event/index.tsx
- src/global-event/tests/unit/GlobalEvent.spec.tsx
Updates `GlobalEvent` widget from class to function based.
Resolves #1183
> Global event function based

- src/calendar/DatePicker.tsx
- src/calendar/tests/unit/DatePicker.spec.tsx
**Type:** bug
Moves the controls div in the date picker so the new styles placing the navigation in the header work
properly.
Resolves #1230
> Fix year navigation styles in date picker

- src/grid/PlaceholderRow.tsx
Grid's placeholderrow was missing theme.variant so would not calculate height correctly.
> Variant fixes

- docs/V7-Migration-Guide.md
Removes chip, context menu, popup, and context popup from the migration guide since they are new widgets
Part of #1240
> Remove some new widgets from migration guide

- src/progress/index.tsx
- src/progress/tests/unit/Progress.spec.tsx
**Type:** bug
Adds the `aria` bundle back in to the `Progress` widget. This was previously removed, but is being added back to keep things standardized until further discussion/changes.
Resolves #1276
> Add aria back to Progress widget

- .dojorc
- package-lock.json
- src/examples/src/config.tsx
- src/examples/src/widgets/list/memoryTemplate.tsx
- src/examples/src/widgets/typeahead/Basic.tsx
- src/examples/src/widgets/typeahead/CustomFilter.tsx
- src/examples/src/widgets/typeahead/RemoteSource.tsx
- src/examples/src/widgets/typeahead/Validation.tsx
- src/examples/src/widgets/typeahead/states.ts
- src/list/index.tsx
- src/select/index.tsx
- src/theme/default/index.ts
- src/theme/default/typeahead.m.css
- src/theme/default/typeahead.m.css.d.ts
- src/theme/dojo/index.ts
- src/theme/dojo/typeahead.m.css
- src/theme/dojo/typeahead.m.css.d.ts
- src/theme/material/index.ts
- src/theme/material/typeahead.m.css
- src/theme/material/typeahead.m.css.d.ts
- src/typeahead/README.md
- src/typeahead/index.tsx
- src/typeahead/tests/unit/Typeahead.spec.tsx
Adding Typeahead widget!
Resolves #795
> Adding typeahead widget (#795)

- docs/V7-Migration-Guide.md
v7 Migration guide for Helper-Text, Icon, and Label
- Removed helper-text and icon due to backwards compatibility; nothing notable for migrating
- Fixed a few typos that I came across
Resolves #1241
> v7 Migration guide for Helper-Text, Icon, and Label

- src/accordion-pane/tests/unit/AccordionPane.spec.tsx
- src/examples/src/widgets/accordion-pane/Basic.tsx
- src/examples/src/widgets/accordion-pane/Exclusive.tsx
- src/examples/src/widgets/title-pane/Basic.tsx
- src/examples/src/widgets/title-pane/HeadingLevel.tsx
- src/examples/src/widgets/title-pane/NonCloseable.tsx
- src/title-pane/index.tsx
- src/title-pane/tests/unit/TitlePane.spec.tsx
> Fix child renderer types for title pane

- docs/V7-Migration-Guide.md
- src/examples/src/widgets/snackbar/Basic.tsx
- src/examples/src/widgets/snackbar/Error.tsx
- src/examples/src/widgets/snackbar/Leading.tsx
- src/examples/src/widgets/snackbar/Stacked.tsx
- src/examples/src/widgets/snackbar/Success.tsx
- src/snackbar/index.tsx
- src/snackbar/tests/unit/Snackbar.spec.tsx
Moved `messageRenderer` and `actionsRenderer` to children as `message` and `actions`
```tsx
<Snackbar open={true}>
{{
message: 'Snackbar',
actions: 'Actions'
}}
</Snackbar>
```
Resolves #1268
> Moved content to child renderers

- src/examples/src/widgets/grid/EditableCells.tsx
**Type:** bug
Updates the column config to be editable in the grid example. The data seems to be persisting fine, so I'm not sure that there's anything else that needs to be done here.
Resolves #1287
> Make editable grid example editable

- src/examples/src/widgets/switch/Basic.tsx
- src/examples/src/widgets/switch/Disabled.tsx
- src/switch/index.tsx
- src/switch/tests/unit/Switch.spec.tsx
Resolves #1269 
Remove `label`, `onLabel`, and `offLabel` from `<Switch>` in favor of an object child with those values.
> Switch: use child properties for the labels

- src/examples/src/widgets/text-area/Disabled.tsx
- src/examples/src/widgets/text-area/HelperText.tsx
- src/examples/src/widgets/text-area/HiddenLabel.tsx
- src/examples/src/widgets/text-area/Label.tsx
- src/examples/src/widgets/text-area/ValidatedCustom.tsx
- src/examples/src/widgets/text-area/ValidatedRequired.tsx
- src/text-area/index.tsx
- src/text-area/tests/unit/TextArea.spec.tsx
> Update textarea to use a child renderer for its label

- src/card/index.tsx
- src/card/tests/unit/Card.spec.tsx
- src/examples/src/widgets/card/ActionButtons.tsx
- src/examples/src/widgets/card/ActionButtonsAndIcons.tsx
- src/examples/src/widgets/card/ActionIcons.tsx
- src/examples/src/widgets/card/Basic.tsx
- src/examples/src/widgets/card/CardCombined.tsx
- src/examples/src/widgets/card/CardWithMediaContent.tsx
- src/examples/src/widgets/card/CardWithMediaRectangle.tsx
- src/examples/src/widgets/card/CardWithMediaSquare.tsx
- src/examples/src/widgets/header-card/ActionCard.tsx
- src/examples/src/widgets/header-card/Basic.tsx
- src/examples/src/widgets/header-card/MediaCard.tsx
- src/header-card/index.tsx
- src/header-card/tests/unit/HeaderCard.spec.tsx
Resolves #1253 and resolves #1260 
- Change the `<Card>` child renderers from functions to static `RenderResult`s
- Convert the `<HeaderCard>` `avatar` from a property to a child property.
```tsx
<Card title="Title">
{{
content: <span>Lorem ipsum</span>
}}
</Card>
```
```tsx
<HeaderCard title="Title" subtitle="Subtitle">
{{
avatar: <Avatar>Q</Avatar>,
content: 'This widget is brought to you by the letter Q'
}}
</HeaderCard>
```
> Card/Header Card child renderer updates

- src/examples/src/widgets/slider/DisabledSlider.tsx
- src/examples/src/widgets/slider/SliderWithCustomOutput.tsx
- src/examples/src/widgets/slider/SliderWithValidityCheck.tsx
- src/slider/index.tsx
- src/slider/tests/unit/Slider.spec.tsx
Updates the slider to use a child render result and render function for label and output respectively. 
Resolves #1267
> Update slider to use child renderers for label and output

- src/examples/src/widgets/header/Basic.tsx
- src/examples/src/widgets/header/Leading.tsx
- src/examples/src/widgets/header/Sticky.tsx
- src/examples/src/widgets/header/Trailing.tsx
- src/header/index.tsx
- src/header/tests/unit/Header.spec.tsx
Changes all header child types to `RenderResult`
Resolves #1259
> Fix header child renderer types

- src/context-popup/index.tsx
- src/context-popup/tests/ContextPopup.spec.tsx
- src/popup/index.tsx
- src/popup/tests/Popup.spec.tsx
- src/trigger-popup/index.tsx
- src/trigger-popup/tests/TriggerPopup.spec.tsx
Simplifies the `Popup` child rendering by removing the child render typing and removing the render function.
Also updates the `Popup` usage in `ContextPopup` and `TriggerPopup`
Resolves #1261
> Update popup child renderer

- src/examples/src/widgets/radio-group/Basic.tsx
- src/examples/src/widgets/radio-group/CustomLabel.tsx
- src/examples/src/widgets/radio-group/CustomRenderer.tsx
- src/examples/src/widgets/radio-group/InitialValue.tsx
- src/radio-group/index.tsx
- src/radio-group/tests/RadioGroup.spec.tsx
The default child renderer becomes `radios` and the label child renderer is added.
Resolves #1263
> Update radio group to use a child renderer for its label

- src/dialog/index.tsx
- src/dialog/tests/unit/Dialog.spec.tsx
- src/examples/src/widgets/dialog/ActionsDialog.tsx
- src/examples/src/widgets/dialog/AlertDialog.tsx
- src/examples/src/widgets/dialog/AnimatedDialog.tsx
- src/examples/src/widgets/dialog/Basic.tsx
- src/examples/src/widgets/dialog/CloseableDialog.tsx
- src/examples/src/widgets/dialog/FocusTrappedDialog.tsx
- src/examples/src/widgets/dialog/ModalDialog.tsx
- src/examples/src/widgets/dialog/UnderlayDialog.tsx
Changes all dialog child properties from functions to `RenderResults`.
Resolves #1258
> Update dialog child renderers

- src/chip/index.tsx
- src/chip/tests/Chip.spec.tsx
- src/examples/src/widgets/chip/Basic.tsx
- src/examples/src/widgets/chip/Clickable.tsx
- src/examples/src/widgets/chip/ClickableClosable.tsx
- src/examples/src/widgets/chip/Closable.tsx
- src/examples/src/widgets/chip/ClosableRenderer.tsx
- src/examples/src/widgets/chip/Disabled.tsx
- src/examples/src/widgets/chip/Icon.tsx
Moves `iconRenderer`, `closeRenderer`, and `label` from being properties to being children.
`iconRenderer` and `closeRenderer` were renamed to `icon` and `closeIcon` be more consistent with other child interfaces. `closeIcon` and `label` both have `RenderResult` types now.
Resolves #1256
> Move chip render props to children

- src/examples/src/widgets/number-input/Basic.tsx
**Type:** bug
Updates the number input example to initialize the displayed value using the same number as is passed as the input's `initialValue`.
Resolves #1286
> Fix default value for number input example

- src/checkbox-group/index.tsx
- src/checkbox-group/tests/CheckboxGroup.spec.tsx
- src/examples/src/widgets/checkbox-group/Basic.tsx
- src/examples/src/widgets/checkbox-group/CustomLabel.tsx
- src/examples/src/widgets/checkbox-group/CustomRenderer.tsx
- src/examples/src/widgets/checkbox-group/InitialValue.tsx
Adds `label` child renderer. Moves previous default child renderer to `checkboxes`.
Resolves #1264
> Move checkbox group label to child renderer

- src/calendar/index.tsx
- src/calendar/tests/unit/Calendar.spec.tsx
- src/calendar/tests/unit/CalendarCell.spec.tsx
- src/calendar/tests/unit/DatePicker.spec.tsx
- src/theme/default/calendar.m.css
- src/theme/default/calendar.m.css.d.ts
- src/theme/dojo/calendar.m.css
- src/theme/dojo/calendar.m.css.d.ts
- src/theme/material/calendar.m.css
- src/theme/material/calendar.m.css.d.ts
Uses `theme.compose` for child icon widgets. Depends on #1233 
Resolves #1219
> Use compose in calendar

- docs/V7-Migration-Guide.md
Adds info about the Progress widget to the migration guide.
Part of #1242
> Add progress info to migration guide

- src/context-menu/index.tsx
- src/context-menu/tests/ContextMenu.spec.tsx
- src/context-popup/index.tsx
- src/context-popup/tests/ContextPopup.spec.tsx
- src/examples/src/widgets/context-popup/Basic.tsx
`trigger` is now a simple `RenderResult` instead of a render function with no arguments.
Resolves #1257
> Make context popup trigger child render property a `RenderResult` 

- docs/V7-Migration-Guide.md
Migration guide for Dialog widget
Related to #1246
> Adding dialog widget migration guide (#1246)

- src/examples/src/widgets/tooltip/Basic.tsx
- src/examples/src/widgets/tooltip/Click.tsx
- src/examples/src/widgets/tooltip/Focus.tsx
- src/tooltip/index.tsx
- src/tooltip/tests/unit/Tooltip.spec.tsx
Updates the tooltip to use a child renderer for content, moves target element to a child renderer named `target`.
Resolves #1274
> Update tooltip to use a child renderer for content

- .dojorc
- src/examples/src/config.tsx
- src/examples/src/widgets/three-column-layout/Basic.tsx
- src/theme/default/index.ts
- src/theme/default/three-column-layout.m.css
- src/theme/default/three-column-layout.m.css.d.ts
- src/theme/dojo/index.ts
- src/theme/dojo/three-column-layout.m.css
- src/theme/dojo/three-column-layout.m.css.d.ts
- src/theme/material/index.ts
- src/theme/material/three-column-layout.m.css
- src/theme/material/three-column-layout.m.css.d.ts
- src/three-column-layout/README.md
- src/three-column-layout/index.tsx
- src/three-column-layout/styles/three-column-layout.m.css
- src/three-column-layout/styles/three-column-layout.m.css.d.ts
- src/three-column-layout/tests/ThreeColumnLayout.spec.tsx
Adds a three column layout. This collapses to a two column layout at a configurable breakpoint that defaults to 1024px. It collapses to only the central column at a configurable breakpoint defaulting to 600px. The Dojo and Material themes both separately size the leading and trailing columns to 320px wide (40 * grid size). Which column collapses first is configurable by specifying the `bias` property but defaults to the trailing column.
Resolves #1151
> Three column layout

- src/middleware/tests/theme.spec.tsx
- src/middleware/theme.tsx
- src/theme/default/index.ts
**Type:** bug 
Fixes password-input styles by fixing theme.compose to work properly with theme variants.
Resolves https://github.com/dojo/widgets/issues/1313
> Theme compose and Password input fixes

- package.json
This PR adds TSC call before dev so that type errors can be caught when running the dev command. 
This will not work on file changes ie. in watch mode.
> Run TSC before dev

- docs/V7-Migration-Guide.md
Addresses part of #1243.
Update the v7 migration document with property changes to the checkbox widget, along with an example demonstrating a migration from v6 to v7.
> Checkbox v7 migration doc updates

- src/examples/src/widgets/radio-group/CustomRenderer.tsx
- src/examples/src/widgets/radio/Events.tsx
- src/examples/src/widgets/radio/Labelled.tsx
- src/radio-group/index.tsx
- src/radio-group/tests/RadioGroup.spec.tsx
- src/radio/README.md
- src/radio/index.tsx
- src/radio/tests/unit/Radio.spec.tsx
Moves label property of Radio widget to an optional child of type RenderResult.
Resolves #1262
> Use child renderer for Radio label

- src/examples/src/widgets/range-slider/Labelled.tsx
- src/examples/src/widgets/range-slider/Required.tsx
- src/range-slider/index.tsx
- src/range-slider/tests/unit/RangeSlider.spec.tsx
Resolves #1265 
Remove the `label` and `output` properties from `RangeSlider` in favor of specifying them as children.
> Update RangeSlider to use child renderers

- docs/V7-Migration-Guide.md
Adds info about the `Radio` and `RadioGroup` widgets to the migration guide. 
Part of #1242
> Radio migration guide

- docs/V7-Migration-Guide.md
Updating time picker and range slider migration guides.
Resolves #1246
> Updating time picker and range slider migration guide (#1246)

- docs/V7-Migration-Guide.md
Removes button and global-event sections due to backwards compatibility. No changes needed.
Part of #1242
> v7 Migration guide updates for button and global-event

- docs/V7-Migration-Guide.md
Resolves #1245 
Add documentation for migrating the Slider, Switch, and Tooltip widgets.
> v7 migration doc updates

- src/examples/src/widgets/select/AdditionalText.tsx
- src/examples/src/widgets/select/Basic.tsx
- src/examples/src/widgets/select/CustomRenderer.tsx
- src/examples/src/widgets/select/DisabledSelect.tsx
- src/examples/src/widgets/select/RequiredSelect.tsx
- src/pagination/index.tsx
- src/select/index.tsx
- src/select/tests/Select.spec.tsx
Moves `label` from property to child renderer
Resolves #1266
> Select: moved label to child renderer

- package-lock.json
- package.json
Update latest dojo dependencies
> Update latest dojo dependencies

- src/examples/src/config.tsx
- src/examples/src/widgets/text-input/Controlled.tsx
- src/number-input/index.tsx
- src/number-input/tests/unit/NumberInput.spec.tsx
- src/text-input/index.tsx
- src/text-input/tests/unit/TextInput.spec.tsx
- Adds `value` to `text-input` properties.
- Adds tests
- Fixes number-input
Resolves #1343
> Optionally Controlled textinput

- src/examples/src/config.tsx
- src/examples/src/widgets/select/Controlled.tsx
- src/select/index.tsx
- src/select/tests/Select.spec.tsx
Adds an optional `value` property to select
Resolves #1339
> Optionally control select

- docs/V7-Migration-Guide.md
- src/calendar/index.tsx
- src/calendar/tests/unit/Calendar.spec.tsx
- src/examples/src/config.tsx
- src/examples/src/widgets/calendar/FullyControlled.tsx
Adds `value`, `month`, and `year` properties to optionally allow the calendar to be fully controlled.
Resolves #1347
> Allow calendar to optionally be controlled

- src/theme/material/calendar.m.css
- src/theme/material/calendar.m.css.d.ts
For material calendar theme:
- adds cursor: pointed where appropriate
- disable user selection
- remove fieldset borders
- center text in dates
> Fix pointer for Calendar in material theme

- src/examples/src/config.tsx
- src/examples/src/widgets/form/Controlled.tsx
- src/form/index.tsx
- src/form/tests/unit/Form.spec.tsx
Adds `value` property to the form widget for a controlled use case. Adds an example that uses the `value` property (which doesn't exist yet) on text inputs. 
Resolves #1333
> Make form controlled

- src/examples/src/config.tsx
- src/examples/src/widgets/text-area/Controlled.tsx
- src/text-area/index.tsx
- src/text-area/tests/unit/TextArea.spec.tsx
Allows a `value` property to be specified to control a text area component.
Resolves #1342
> Controlled text area

- src/examples/src/config.tsx
- src/examples/src/widgets/tab-controller/Controlled.tsx
- src/tab-controller/index.tsx
- src/tab-controller/tests/unit/TabController.spec.tsx
In addition to the changes mentioned in the ticket, I added an `onActiveTab` callback.
Resolves #1341
> Allow tab controller to be controlled

- package-lock.json
- package.json
- src/examples/src/widgets/slide-pane/Basic.tsx
- src/examples/src/widgets/slide-pane/BottomAlignSlidePane.tsx
- src/examples/src/widgets/slide-pane/FixedWidthSlidePane.tsx
- src/examples/src/widgets/slide-pane/LeftAlignSlidePane.tsx
- src/examples/src/widgets/slide-pane/RightAlignSlidePane.tsx
- src/examples/src/widgets/slide-pane/UnderlaySlidePane.tsx
- src/examples/src/widgets/slide-pane/common.ts
- src/slide-pane/index.tsx
- src/theme/default/slide-pane.m.css
- src/theme/default/slide-pane.m.css.d.ts
- src/theme/material/slide-pane.m.css
**Type:** bugfix
This pull request adds a material theme for the `SlidePane` widget.
Resolves #1317
**Preview:**
> fix: SlidePane material theme

- src/examples/src/widgets/pagination/SiblingCount.tsx
- src/pagination/index.tsx
- src/pagination/tests/Pagination.spec.tsx
- src/theme/default/index.ts
- src/theme/default/pagination.m.css
- src/theme/default/pagination.m.css.d.ts
- src/theme/dojo/pagination.m.css
- src/theme/dojo/pagination.m.css.d.ts
- src/theme/material/pagination.m.css
- src/theme/material/pagination.m.css.d.ts
DRAFT: some unit tests are missing an implementation
Pagination widget now responsive by automatically removing sibling links when space is insufficient to render `siblingCount` links.
When `siblingCount` is unset, all siblings are included which will fit the available space.
Resolves #1239
> Pagination: automatically remove sibling links as space permits

- src/examples/src/config.tsx
- src/examples/src/widgets/radio-group/Controlled.tsx
- src/radio-group/index.tsx
- src/radio-group/middleware.ts
- src/radio-group/tests/RadioGroup.spec.tsx
Adds back a `value` property to allow optionally controlling the radio group.
Resolves #1337
> Optionally control radio group

- src/examples/src/widgets/pagination/Controlled.tsx
- src/pagination/index.tsx
- src/pagination/tests/Pagination.spec.tsx
Allows pagination to be controlled using `page` and `pageSize` properties.
Resolves #1336
> Optionally control pagination

- src/examples/src/widgets/list/Controlled.tsx
- src/list/index.tsx
- src/list/tests/List.spec.tsx
Adds a controlled `value` property to the list
Resolves #1334
> Optionally control list selection

- src/theme/material/calendar.m.css
Adds a 4% opacity background to hovered dates in the calendar material theme. To my eye I'm not sure if this looks exactly the same as the opacity in the spec for the calendar. But I don't believe they listed a specific value and this is the general value listed for a hover state.
Resolves #1361
> Add hover style to date picker

- docs/V7-Migration-Guide.md
> Update migration guide for TextArea and TextInput

- docs/V7-Migration-Guide.md
Continues #1243 
Update the v7 migration guide with property and structural changes to the tab controller widget, and add an example demonstrating the differences between v6 and v7.
> TabController v7 migration doc updates

- docs/V7-Migration-Guide.md
- src/examples/src/config.tsx
- src/examples/src/widgets/range-slider/Controlled.tsx
- src/range-slider/index.tsx
- src/range-slider/tests/unit/RangeSlider.spec.tsx
Adds `value` prop to `RangeSlider` widget to allow the option for it to be controlled.
Resolves #1338
> Make range-slider optionally controlled

- src/chip/index.tsx
- src/chip/tests/Chip.spec.tsx
- src/theme/default/chip.m.css
- src/theme/default/chip.m.css.d.ts
- src/theme/material/chip.m.css
Fixing material theme for Chip. The close icon was too big!
Resolves #1356
> Fixing chip material theme

- src/theme/material/tooltip.m.css
Fixing Tooltip material styles.
> Fixing tooltip material style

- src/date-input/index.tsx
- src/date-input/tests/unit/DateInput.spec.tsx
- src/examples/src/config.tsx
- src/examples/src/widgets/date-input/Controlled.tsx
Adds `value` property to optionally control the date input
Resolves #1332
> Optionally control date input

- src/checkbox-group/index.tsx
- src/checkbox-group/middleware.tsx
- src/checkbox-group/tests/CheckboxGroup.spec.tsx
- src/examples/src/config.tsx
- src/examples/src/widgets/checkbox-group/Controlled.tsx
Adds `value` property and allows Checkbox Group to be controlled.
Resolves #1331
> Optionally controlled checkbox group

- src/examples/src/config.tsx
- src/examples/src/widgets/native-select/ControlledNativeSelect.tsx
- src/native-select/index.tsx
- src/native-select/tests/NativeSelect.spec.tsx
Will need to update migration guide PR #1329 
Allows native-select to be controlled. Adds `value` property.
Resolves #1335
> Optionally controlled native select

- src/examples/src/config.tsx
Fixing the Basic and Remote Source typeahead examples to include the actual example code 😄
> Fixing typeahead examples

- src/examples/src/config.tsx
Fixing missing code in parade examples for 
- HeaderCard
- ThreeColumnLayout
- TitlePane
> Fixing parade examples for various widgets

- src/theme/default/tooltip.m.css
- src/theme/dojo/tooltip.m.css
- src/theme/material/tooltip.m.css
- src/tooltip/styles/tooltip.m.css
**Type:** bug
Adds `whitespace: nowrap` to keep the tooltip to a single line. Moves the transform styles to the default theme so that the dojo and material theme overrides actually take effect. Removes the margin styles that don't have any effect on the tooltip given its absolute positioning.
Resolves #1385
> Fix material tooltip spacing

- src/examples/src/config.tsx
- src/slide-pane/styles/slide-pane.m.css
- src/theme/default/slide-pane.m.css
- src/theme/dojo/slide-pane.m.css
- src/theme/dojo/variants/default.m.css
- src/theme/material/slide-pane.m.css
**Type:** bug
There were some "fixed" styles that were inaccessible via theme composure. They have been moved to the default theme to allow theme overriding. As before, the slidepane is still functional with the default theme.
Increased sandbox size to better represent how slidepane looks/works in examples.
Resolves #1387
> Removed "fixed" styles to allow theme control over sliding

- src/examples/src/config.tsx
- src/examples/src/widgets/list/Disabled.tsx
- src/examples/src/widgets/radio-group/CustomRenderer.tsx
- src/list/index.tsx
- src/list/tests/List.spec.tsx
Adding a `disabled` property to List to give an injection point into disabling items.
Resolves #1392
> Adding disabled property to list (#1392)

- src/theme/default/dialog.m.css
- src/theme/default/grid-cell.m.css
- src/theme/dojo/list.m.css
- src/theme/dojo/list.m.css.d.ts
- src/theme/dojo/native-select.m.css
Fixing some undefined CSS vars.
> Fixing some styles

- src/examples/src/widgets/date-input/Basic.tsx
Fixing broken date input example
> Fixing broken DateInput example

- src/examples/src/widgets/snackbar/Stacked.tsx
- src/theme/material/raised-button.m.css.d.ts
- src/theme/material/slide-pane.m.css
- src/theme/material/slide-pane.m.css.d.ts
Fixing some material theme issues with right side slide pane, underlay slide pane,  and stacked snackbar example.
Resolves #1404
> Fixing snackbar and slide pane material styles

- .dojorc
- src/examples/src/config.tsx
- src/tab-container/index.tsx
- src/tab-container/tests/TabContainer.spec.tsx
- src/theme/default/tab-container.m.css
**Type:** bug
The `TabController` was renamed `TabContainer` but lots of references were missed, including the widget in the `.dojorc`
> Update References to TabController to TabContainer

- src/accordion/index.tsx
- src/accordion/tests/unit/Accordion.spec.tsx
- src/examples/src/widgets/accordion/Basic.tsx
- src/examples/src/widgets/accordion/Exclusive.tsx
- src/examples/src/widgets/title-pane/Basic.tsx
- src/examples/src/widgets/title-pane/Controlled.tsx
- src/examples/src/widgets/title-pane/HeadingLevel.tsx
- src/examples/src/widgets/title-pane/NonCloseable.tsx
- src/title-pane/index.tsx
- src/title-pane/tests/unit/TitlePane.spec.tsx
Following on from changes to Tab Container, Accordion has been given the same treatment.
> Simplify accordion

- src/examples/src/widgets/form/ActionForm.tsx
- src/examples/src/widgets/form/Basic.tsx
- src/examples/src/widgets/form/Controlled.tsx
- src/examples/src/widgets/form/DisabledFieldsForm.tsx
- src/examples/src/widgets/form/DisabledForm.tsx
- src/examples/src/widgets/form/FillingForm.tsx
- src/examples/src/widgets/form/InitialValueForm.tsx
- src/examples/src/widgets/form/KitchenSinkForm.tsx
- src/examples/src/widgets/form/RequiredFieldsForm.tsx
- src/examples/src/widgets/form/ResettingForm.tsx
- src/examples/src/widgets/form/SubmitForm.tsx
- src/examples/src/widgets/form/Validation.tsx
- src/form/index.tsx
- src/form/tests/unit/Form.spec.tsx
- src/theme/default/form.m.css
- src/theme/default/index.ts
- src/theme/dojo/form.m.css
- src/theme/dojo/form.m.css.d.ts
- src/theme/dojo/index.ts
- src/theme/material/form.m.css
- src/theme/material/form.m.css.d.ts
- src/theme/material/index.ts
This pull request adds two supporting widgets meant to ease the layout of form fields: `FormGroup` and `FormField`. This initial implementation is straightforward: a form group can render its children horizontally or vertically with uniform spacing.
Resolves #1085 
**Preview:**
> feat: FormGroup and FormField

- src/chip-typeahead/index.tsx
- src/chip-typeahead/tests/unit/ChipTypeahead.spec.tsx
- src/examples/src/config.tsx
- src/examples/src/widgets/chip-typeahead/FreeText.tsx
- src/examples/src/widgets/typeahead/FreeText.tsx
- src/theme/dojo/form.m.css.d.ts
- src/theme/material/form.m.css.d.ts
- src/typeahead/index.tsx
- src/typeahead/tests/unit/Typeahead.spec.tsx
- Adds `strict` property to `Typeahead` and `ChipTypeahead`.
- Allows non-resource values to be entered.
- Adds examples
- Adds tests
Resolves #1416
> Allow typeahead to take free text

- src/theme/default/form.m.css
- src/theme/dojo/form.m.css
- src/theme/material/form.m.css
This pull request updates the `FormGroup` and `FormField` widgets so they have a minimum width and wrap in a responsive manner based on the size of their parent.
Reference #1419
**Preview:**
> feat: responsive form fields

- package-lock.json
- package.json
- src/examples/src/config.tsx
- src/theme/dojo/variants/default.m.css
- src/theme/material/variants/default.m.css
Support theme variants in parade.
> Support theme variants in parade

- src/examples/src/widgets/avatar/Basic.tsx
- src/examples/src/widgets/avatar/Icon.tsx
- src/examples/src/widgets/avatar/Image.tsx
- src/examples/src/widgets/avatar/Secondary.tsx
- src/examples/src/widgets/avatar/Size.tsx
- src/examples/src/widgets/avatar/Variant.tsx
- src/examples/src/widgets/card/ActionButtons.tsx
- src/examples/src/widgets/card/ActionButtonsAndIcons.tsx
- src/examples/src/widgets/card/ActionIcons.tsx
- src/examples/src/widgets/card/Basic.tsx
- src/examples/src/widgets/card/CardCombined.tsx
- src/examples/src/widgets/card/CardWithMediaContent.tsx
- src/examples/src/widgets/card/CardWithMediaRectangle.tsx
- src/examples/src/widgets/header-card/ActionCard.tsx
- src/examples/src/widgets/header-card/Basic.tsx
- src/examples/src/widgets/header-card/MediaCard.tsx
These set widths are causing issues with some example layouts.
This PR changes them to max-width instead.
> mobile improvements: Remove set widths from examples

- src/examples/src/widgets/checkbox/Basic.tsx
**Type:** bug 
Example description says
> Sample checkbox that starts checked
But checked was `false`
> Example should start `checked`

- package-lock.json
- package.json
- src/examples/src/config.tsx
Make the deployment ie11 compatible.
> Deploy ie11 compatible docs

- src/chip-typeahead/index.tsx
- src/chip-typeahead/tests/unit/ChipTypeahead.spec.tsx
- src/typeahead/index.tsx
- src/typeahead/tests/unit/Typeahead.spec.tsx
**Type:** bug
Fixes behavior when a matched option does not have a label, and forces duplicates to be allowed when in non-strict mode for the chip typeahead.
> Fix typeahead

- src/theme/material/tooltip.m.css
**Type:** bug
Tooltip Material theme was using an old variable name which no longer exists. It was causing positional issues which, among other things, presented a flickering issue.
Resolves #1447
> Fixed missing variables in Tooltip material theme

- src/list/index.tsx
- src/list/tests/List.spec.tsx
If the list is marked as `focusable` false, ignore pointer down events so the list does not become focusable when scrolling.
Resolves #1449
> Unfocusable list no longer focuses on scroll

- src/examples/src/widgets/trigger-popup/Basic.tsx
- src/examples/src/widgets/trigger-popup/SetWidth.tsx
- src/examples/src/widgets/trigger-popup/Underlay.tsx
**Type:** bug
The `onpointerleave` implementation was too trivial for it to work consistently enough in this case. The default behavior of TriggerPopup is sufficient for these examples, so I'm just removing them.
Resolves #1448
> Removed trivial `onpointerleave` from examples

- src/grid/index.tsx
- src/grid/tests/unit/Grid.spec.tsx
- src/grid/tests/unit/Row.spec.tsx
**Type:** bugfix
This pull request updates the `Grid` widget by fixing a bug in paginated grids that prevented row selection from working properly.
Resolves #1436 
**Preview:**
> fix: paginated grid row selection

- src/time-picker/index.tsx
- src/time-picker/tests/unit/TimePicker.spec.tsx
**Type:** bug
IE injects invisible unicode characters into the output of `toLocaleTimeString`, which breaks the regex.
> Fix format time in IE 11

- src/theme/dojo/list-item.m.css
- src/theme/dojo/menu-item.m.css
- src/theme/material/list-item.m.css
- src/theme/material/menu-item.m.css
**Type:** bugfix
This pull request adds list item text wrapping to the Dojo and Material themes.
Resolves #1457 
**Preview:**
> fix: wrap list item result text

- src/grid/index.ts
- src/grid/tests/unit/Grid.ts
- src/grid/tests/unit/Row.ts
**Type:** bugfix
This pull request back-ports grid-related fixes from #1439 to `@dojo/widgets@^6.2.0`.
References #1461
> fix: paginated grid row selection (#1439)

- src/theme/material/chip-typeahead.m.css
- src/theme/material/chip-typeahead.m.css.d.ts
Fixes mis-aligned text input for chip-typeahead and ensures the height does not jump when chips are added.
> Fix Material Chip typeahead styles

- src/tab-container/index.tsx
- src/tab-container/tests/TabContainer.spec.tsx
- src/theme/dojo/tab-container.m.css
- src/theme/material/tab-container.m.css
**Type:** bug
Replaced tab "close" with Icon:
Dojo Theme:
Material Theme:
Resolves #1468
> Fixed broken Material tab theme

- .dojorc
**Type:** bug
Adds the result widget to `.dojorc`
Resolves #1475
> Add result widget to dojorc

- src/theme/dojo/range-slider.m.css
**Type:** bug
Adjusted input height & thumb positioning. Material theme is working correctly, so ported some styles from there to Dojo.
Resolves #1477
> Fixed styling issues with range-slider interaction

- src/list/index.tsx
- src/list/tests/ListItem.spec.tsx
- src/list/tests/MenuItem.spec.tsx
Changes the `pointerdown` handler to an `onclick` handler to allow pointer scroll events.
Resolves #1485
> Fix mobile scrolling on lists

- src/range-slider/index.tsx
- src/range-slider/tests/unit/RangeSlider.spec.tsx
- src/theme/dojo/range-slider.m.css
- src/theme/dojo/slider.m.css
**Type:** bug
Tweaks to both Slider and RangeSlider to consolidate their styling and interaction.
1. CSS fixes to Slider to correctly position `input` for proper interaction
2. Fixed RangeSlider focus detection to properly apply focus styles
Resolves #1491
> Consolidate Slider & RangeSlider styles/interactions

- src/examples/src/widgets/chip-typeahead/Basic.tsx
- src/examples/src/widgets/chip-typeahead/BottomPlacement.tsx
- src/examples/src/widgets/chip-typeahead/FreeText.tsx
- src/examples/src/widgets/date-input/Basic.tsx
**Type:** bug
Fixes import paths to other example files in examples
Resolves #1476
> Fix example imports in examples

- docs/V7-Migration-Guide.md
Add example of creating a collapsible header that repliates the previous `Toolbar` functionality using a header and a slide pane.
> Add example of Collapsible Header using toolbar using Header and SlidePane

- docs/V7-Migration-Guide.md
Adds an example of using a resource widget (Select) within a class-based widget parent.
This uses the resource-wrapper founds [here](https://github.com/agubler/dojo-resource-wrapper)
> Add example of using resources within a class based widget to migration guide

- src/form/index.tsx
- src/form/tests/unit/Form.spec.tsx
- src/tab-container/index.tsx
- src/tab-container/tests/TabContainer.spec.tsx
- src/text-input/index.tsx
- src/text-input/tests/unit/TextInput.spec.tsx
**Type:** bug
Fixes types when using multiple children with `w` for `tab-container`, `Addon` from `TextInput`, and `FormField` from `Form` 
Resolves #1500
> Fix multichild types

- package-lock.json
**Type:** Bug
Bumps cli-build-app version from `7.0.2` to `7.0.1` since `7.0.2` had to be unpublished
> Bump cli-build-app version from 7.0.2 to 7.0.1

- .dojorc
**Type:** Bug
Removes zh-TW from supported locales to resolve issues with vercel deployment
> Removes zh-TW from supported locales

- src/grid/styles/grid.m.css
**Type:** bug
Removes `height: 100%` from the grid's fixed css for the header
Resolves #1517
> Remove height 100% from grid header

- .dojorc
- package-lock.json
- package.json
- src/two-column-layout/tests/TwoColumnLayout.spec.tsx
Bumps build-app version to fix locale building issues. This enables the `zh-TW` bundle again.
> Bump build app version and restore zh-TW bundle

- src/list/index.tsx
- src/list/tests/List.spec.tsx
- src/typeahead/index.tsx
- src/typeahead/tests/unit/Typeahead.spec.tsx
- `List` should not render root node when it has no items.
- `Typeahead` should pass `classes` to `List`
- `List` should pass `classes` to both `ListItem` and `MenuItem`
Resolves #1530 
Resolves #1532
> List & Typeahead fixes

- src/accordion/index.tsx
Rename Accordion function from LoadingIndicator to Accordion
Fixes #1537
> Fix typo: rename Accordion function to Accordion

- src/slide-pane/styles/slide-pane.m.css
- src/theme/dojo/slide-pane.m.css
- src/theme/dojo/slide-pane.m.css.d.ts
- src/theme/material/slide-pane.m.css
- src/theme/material/slide-pane.m.css.d.ts
Fixes an issue with SlidePane when the theme was imported _after_ the SlidePane. This will change the order of the CSS and things weren't being applied in the right order.
Resolves #1522
> Updating slidepane css to not be dependent on theme import order (#1522)

- .dojorc
- src/examples/src/config.tsx
- src/examples/src/widgets/list/Draggable.tsx
- src/list/index.tsx
- src/list/tests/List.spec.tsx
- src/list/tests/ListItem.spec.tsx
- src/theme/default/list-item.m.css
- src/theme/default/list-item.m.css.d.ts
- src/theme/dojo/list-item.m.css
- src/theme/dojo/list-item.m.css.d.ts
- src/theme/material/list-item.m.css
- src/theme/material/list-item.m.css.d.ts
This pull request augments the existing resource-powered `List` widget by adding the ability to drag-and-drop reorder items. This work implements a completely different approach to that in #1547, the latter of which did not build upon `List` or use resources.
Resolves #1429
**Preview:**
> feat: DraggableList v2

- package-lock.json
- src/common/tests/support/test-helpers.ts
- src/tree/index.tsx
- src/tree/tests/unit/Tree.spec.tsx
Changes to ensure that assertion templates can target wrapped nodes within functional children mean that we need to update the Tree tests to actually test the children (which is correct regardless).
Also fixes the types for a harness abstraction.
> Update widgets to latest framework v7 patch release

- src/examples/src/widgets/grid/Restful.tsx
**Type:** bug
The old mock server used no longer worked, updated to the same server as the advanced examples.
> Update Restful Grid Example

- src/examples/src/widgets/list/Basic.tsx
- src/list/index.tsx
- src/list/tests/List.spec.tsx
**Type:** bug
At the moment the list "controls" the size of the resource page based on the number of items that need to be rendered. This is bad when options are passed to the list with a custom page size set, it overrides the page size requested by the user. Instead this change calculates the number of items required for rendering and then uses the existing page size to determine how many pages need to be requested to fulfil each page.
> Decouple the list rendered page size from the resource request size

- src/middleware/theme.tsx
**Type:** bug
This deals correctly with classes when using the theme middleware.
> Better guard for dealing with classes

- .dojorc
- src/action-button/README.md
- src/action-button/index.tsx
- src/action-button/tests/unit/ActionButton.spec.tsx
- src/avatar/index.tsx
- src/avatar/tests/unit/Avatar.spec.tsx
- src/examples/src/config.tsx
- src/examples/src/widgets/action-button/Basic.tsx
- src/examples/src/widgets/action-button/example.m.css
- src/examples/src/widgets/action-button/example.m.css.d.ts
- src/examples/src/widgets/avatar/Icon.tsx
- src/examples/src/widgets/avatar/Image.tsx
- src/examples/src/widgets/avatar/Secondary.tsx
- src/examples/src/widgets/avatar/Variant.tsx
- src/examples/src/widgets/snackbar/Stacked.tsx
- src/middleware/tests/theme.spec.tsx
- src/middleware/theme.tsx
- src/theme/material/snackbar.m.css
- src/theme/material/variants/default.m.css
Proof of concept that introduces a property from the widget `theme` middleware to prevent applying the `theme.variant` class to the root meaning that widgets will instead inherit the variable properties from a parent. This allows variables to be partially overridden falling back to the standard set that are applied either at the root of the composite widget or the root of the application.
Unfortunately there was a clash of the property name with the `Avatar` widget that also used `variant` for a different purpose, this property has been renamed `type` and therefore makes this a breaking changes.
Also introduces a new widget `ActionButton` that sets the `variant` property to inherit that should be used for …
> Support capability to indicate widgets should inherit css vars for the variant from a parent

- .dojorc
- src/examples/src/config.tsx
- src/examples/src/tests.tsx
**Type:** bug
Codesandbox fails for the require.context usage and the import of the default theme (it's not published). These changes should fix codesandbox and also work as expected for parade builds.
> Fix codesandbox for parade examples

- src/examples/src/widgets/form/ActionForm.tsx
- src/examples/src/widgets/form/Basic.tsx
- src/examples/src/widgets/form/Controlled.tsx
- src/examples/src/widgets/form/DisabledFieldsForm.tsx
- src/examples/src/widgets/form/DisabledForm.tsx
- src/examples/src/widgets/form/FillingForm.tsx
- src/examples/src/widgets/form/InitialValueForm.tsx
- src/examples/src/widgets/form/KitchenSinkForm.tsx
- src/examples/src/widgets/form/RequiredFieldsForm.tsx
- src/examples/src/widgets/form/ResettingForm.tsx
- src/examples/src/widgets/form/SubmitForm.tsx
- src/examples/src/widgets/form/Validation.tsx
- src/form/middleware.ts
- src/form/tests/unit/Form.spec.tsx
Overload the form middleware children function API to be a function factory that returns the API - this means that consumers do not need to import the `FormMiddleware` interface to get the typings, instead use the factory function and pass the field interface.
```ts
const { field } = form<Fields>();
```
Resolves #1582
> Make the form api typing more ergonomic

- src/list/index.tsx
- src/list/tests/List.spec.tsx
- src/middleware/offscreen.ts
A middleware that renders nodes offscreen and executes a function on the root node returning the result, using the applications base registry to ensure that theming and other global aspects are applied.
> Offscreen middleware

- src/examples/src/widgets/select/Controlled.tsx
- src/select/index.tsx
- src/select/tests/Select.spec.tsx
**Type:** bug
Use the associated label for the id passed as the initial value or controlled value
> Ensure that the id is used to get the label for async templates

- src/list/index.tsx
- src/list/tests/List.spec.tsx
**Type:** bug
The list should be rendered to the requested size of the items in view, by default 10. This will prevent the list "popping" in once items have been fetched.
> Render list shell based on the item size and items in view

- src/context-menu/index.tsx
- src/context-menu/tests/ContextMenu.spec.tsx
- src/examples/src/widgets/select/Basic.tsx
- src/list/index.tsx
- src/list/tests/List.spec.tsx
- src/select/index.tsx
- src/select/tests/Select.spec.tsx
- src/time-picker/index.tsx
- src/time-picker/tests/unit/TimePicker.spec.tsx
- src/typeahead/index.tsx
- src/typeahead/tests/unit/Typeahead.spec.tsx
The height of the list should be able to shrink to fit if there are less items than the specified items in view, this is for widgets such as the select and typeahead. By default the list will take up all the space required to fix the number of items in view in.
> Add property to configure the list to be able to set the height to auto

- src/chip-typeahead/index.tsx
- src/chip-typeahead/tests/unit/ChipTypeahead.spec.tsx
- src/common/tests/support/test-helpers.ts
- src/examples/src/widgets/typeahead/FreeText.tsx
- src/typeahead/index.tsx
- src/typeahead/tests/unit/Typeahead.spec.tsx
**Type:** bug
This fixes behaviours related to non strict mode, controlled values and item labels
> Fix typeahead and chip-typeahead behaviours

- src/theme/material/helper-text.m.css
**Type:** bug
Helper text has to wrap as there is no set width it cannot be truncated.
> Wrap Helper Text

- src/examples/src/widgets/typeahead/FreeText.tsx
- src/typeahead/index.tsx
- src/typeahead/tests/unit/Typeahead.spec.tsx
**Type:** bug
Fixes issues relating to the Typeahead non-strict behaviour
Resolves #1620
Resolves #1621
> Bug: Fixes non-strict Typeahead behaviour related to onValue and validation

- src/typeahead/index.tsx
- src/typeahead/tests/unit/Typeahead.spec.tsx
**Type:** bug
Changes the behaviour to only check for matching items when the template is not loading.
Resolves #1625
> Fix filtering and selecting an item in non-strict mode when a template is loading

- src/theme/material/checkbox.m.css
- src/theme/material/variants/dark.m.css
- src/theme/material/variants/default.m.css
Introduces `--mdc-checkbox-background-enabled` `--mdc-checkbox-background-checked` and `--mdc-checkbox-check` variables to customize checkbox colors when using the material theme.
Resolves #1630
> Add variables to customize checkbox

- src/theme/material/chip.m.css
- src/theme/material/variants/dark.m.css
- src/theme/material/variants/default.m.css
Adds a variable for the chip color in the material theme
Resolves #1633
> Add variable for chip color

- src/examples/src/config.tsx
- src/examples/src/widgets/wizard/Basic.tsx
- src/examples/src/widgets/wizard/Custom.tsx
- src/examples/src/widgets/wizard/Error.tsx
- src/examples/src/widgets/wizard/Vertical.tsx
- src/wizard/index.tsx
- src/wizard/tests/unit/Wizard.spec.tsx
Adding additional widget customization options by using a custom renderer for the wizard steps. Also removing the `Step` widget as it is now just part of the custom renderer.  The widget also now takes a `steps` property that defines the step data. This pattern comes from tab container / checkbox group.
Resolves #1636
> Refactoring wizard to be more customizable

- src/button/index.tsx
- src/button/tests/unit/Button.spec.tsx
- src/examples/src/config.tsx
- src/examples/src/widgets/button/Kinds.tsx
- src/examples/src/widgets/outlined-button/Kinds.tsx
- src/examples/src/widgets/raised-button/Kinds.tsx
- src/theme/default/button.m.css
- src/theme/default/button.m.css.d.ts
- src/theme/dojo/button.m.css
- src/theme/dojo/button.m.css.d.ts
- src/theme/dojo/outlined-button.m.css
- src/theme/dojo/outlined-button.m.css.d.ts
- src/theme/dojo/raised-button.m.css
- src/theme/dojo/raised-button.m.css.d.ts
- src/theme/dojo/variants/default.m.css
- src/theme/material/button.m.css
- src/theme/material/button.m.css.d.ts
- src/theme/material/outlined-button.m.css
- src/theme/material/outlined-button.m.css.d.ts
- src/theme/material/raised-button.m.css
- src/theme/material/raised-button.m.css.d.ts
Adding button kinds "secondary" and "cancel" and corresponding styles.
Resolves #1637
> Adding button kinds

- src/theme/material/tab-container.m.css
resolves #1650
Fixing an issue that makes nothing clickable inside of a TabContainer.
Resolves #1650
> moving mdc-tab__content class from tab body to tab itself.

- src/theme/material/tab-container.m.css
Backport of tab container fix!
> moving mdc-tab__content class from tab body to tab itself. (#1651)

- src/theme/material/select.m.css
- src/theme/material/text-input.m.css
**Type:** bug
- Updates the `border-bottom-color` on the `Select` widget material theme to match coloring of other input widgets
- Updates placeholder color for `TextInput` widget with material theme to be the same color as the label of the `Select` widget with material theme.
Resolves #1629
> Update form input widget material theme

- src/text-input/index.tsx
- src/text-input/tests/unit/TextInput.spec.tsx
Updates `TextInput` widget so it will not show errors before the user interacts with the input. This was happening when a `TextInput` widget used the onValidate and valid fields and had required marked as `true`. You can view the error here: https://widgets.dojo.io/#widget/text-input/example/validated
Resolves #1580
> Updated text input to not show error by default

- src/date-input/index.tsx
- src/date-input/tests/unit/DateInput.spec.tsx
- src/examples/src/widgets/date-input/Basic.tsx
**Type:** bug
Stops the date input from defaulting the value to todays date and adds support to clear the input.
Resolves #1661
> Do no default the input to todays date and support clearing the date input

- src/time-picker/index.tsx
- src/time-picker/tests/unit/TimePicker.spec.tsx
**Type:** bug
The options for the time-picker are created every render, this is super costly and causes issues through out applications.
> Cache things to make the current timepicker usable

- src/date-input/index.tsx
- src/date-input/tests/unit/DateInput.spec.tsx
- src/examples/src/widgets/form/SubmitForm.tsx
- src/time-picker/index.tsx
- src/time-picker/tests/unit/TimePicker.spec.tsx
**Type:** bug
When using the inputs as part of a form the setting of the values on "Enter" was actually done on the next render, which meant that the submit of the form happened with "stale" data before it was updated. This changes to set the value immediately so it is correct for a form submission
> Fix setting values in date input and time picker when submitting as part of the form

- src/text-input/index.tsx
- src/text-input/tests/unit/TextInput.spec.tsx
- src/theme/default/text-input.m.css
- src/theme/default/text-input.m.css.d.ts
- src/theme/material/text-input.m.css
- src/theme/material/text-input.m.css.d.ts
**Type:** bug
Use keyframes to trigger an event when 
Resolves #1610
> add text-input autocomplete hook

- src/examples/src/widgets/loading-indicator/Basic.tsx
- src/loading-indicator/README.md
- src/loading-indicator/index.tsx
- src/loading-indicator/tests/unit/LoadingIndicator.spec.tsx
- src/theme/default/loading-indicator.m.css
- src/theme/default/loading-indicator.m.css.d.ts
- src/theme/dojo/loading-indicator.m.css
- src/theme/dojo/loading-indicator.m.css.d.ts
- src/theme/material/loading-indicator.m.css
- src/theme/material/loading-indicator.m.css.d.ts
Adds an active property to the loading indicator. When the active property is false, the loading bar is hidden. This allows easily hiding the loading indicator without shifting the page layout.
Resolves #1608
> Loading-indicator active property

- src/examples/src/config.tsx
- src/examples/src/widgets/number-input/LeadingTrailing.tsx
This adds a leading/trailing example for the number input widget.
Relates to #1578 which indicated a styling issue with the NumberInput
> Add leading/trailing example for NumberInput

- src/date-input/tests/unit/DateInput.spec.tsx
- src/tab-container/index.tsx
- src/tab-container/tests/TabContainer.spec.tsx
- src/theme/default/tab-container.m.css
- src/theme/default/tab-container.m.css.d.ts
- src/theme/dojo/tab-container.m.css
- src/theme/dojo/tab-container.m.css.d.ts
- src/theme/dojo/variants/dark.m.css
- src/theme/dojo/variants/default.m.css
- src/theme/material/tab-container.m.css
- src/theme/material/tab-container.m.css.d.ts
- src/theme/material/variants/dark.m.css
- src/theme/material/variants/default.m.css
Adds more specific CSS variables that allow control of tab colours and backgrounds, defaulting to the current CSS variables used.
> Add specific css variables to control tab colors

- src/examples/src/widgets/form/KitchenSinkForm.tsx
- src/theme/dojo/time-picker.m.css
- src/trigger-popup/trigger-popup.m.css
**Type:** bug
Set the trigger to full width, it will be controlled by the content.
Resolves #1579
> Set trigger input to full width

- src/text-input/index.tsx
- src/text-input/tests/unit/TextInput.spec.tsx
Auto complete off by default for inputs
> Auto complete off by default for inputs

- src/examples/src/widgets/slide-pane/Basic.tsx
- src/examples/src/widgets/slide-pane/BottomAlignSlidePane.tsx
- src/examples/src/widgets/slide-pane/FixedWidthSlidePane.tsx
- src/examples/src/widgets/slide-pane/LeftAlignSlidePane.tsx
- src/examples/src/widgets/slide-pane/RightAlignSlidePane.tsx
- src/examples/src/widgets/slide-pane/UnderlaySlidePane.tsx
- src/slide-pane/index.tsx
- src/slide-pane/tests/unit/SlidePane.spec.tsx
Changes the title for the slidepane to be a child over a property so that a render result can be used.
> Allow the slidepane title to be a render result

- src/theme/dojo/dialog.m.css
- src/theme/material/dialog.m.css
> Make dialog close icons square

- src/theme/material/card.m.css
**Type:** bug
Allows material card title margin styles if it is the first element. To do so we need to check that there isn't a media element or header before the title.
Resolves #1588
> fix material card header margin

- src/theme/dojo/floating-action-button.m.css
- src/theme/dojo/variants/default.m.css
- src/theme/material/floating-action-button.m.css
- src/theme/material/variants/default.m.css
This pull request uses variables that are specific to the `FloatingActionButton` so that basic theming (background color and text color, for now) is easier. Previously, `Button` defaults were used, which prevented buttons and FABs from being themed independently.
Resolves #1649
> feat: easier FloatingActionButton theming

- src/theme/default/wizard.m.css
- src/theme/dojo/wizard.m.css
- src/theme/material/wizard.m.css
This pull request fixes vertical wizard rendering and base responsiveness by wrapping flex appropriately.
Resolves #1615
Resolves #1616
> fix: wizard styling and responsiveness

- src/avatar/tests/unit/Avatar.spec.tsx
- src/button/tests/unit/Button.spec.tsx
- src/calendar/tests/unit/Calendar.spec.tsx
- src/helper-text/tests/unit/HelperText.spec.tsx
- src/number-input/tests/unit/NumberInput.spec.tsx
- src/pagination/tests/Pagination.spec.tsx
- src/popup/tests/Popup.spec.tsx
- src/slide-pane/tests/unit/SlidePane.spec.tsx
- src/slider/tests/unit/Slider.spec.tsx
- src/snackbar/tests/unit/Snackbar.spec.tsx
**Type:** refactor
Updates tests to not pass raw arrays. This removes warnings from unit tests and helps avoid mutation.
> fix test warnings

- src/result/index.tsx
- src/tooltip/index.tsx
- src/tooltip/tests/unit/Tooltip.spec.tsx
**Type:** bug 
This PR 
- deprecates tooltip position enum
- allows tooltip to accept a position string
- removes unused, exported result widget enum 
Resolves #555
> [555] Fix exported Enums for properties

- src/examples/src/config.tsx
- src/examples/src/widgets/list/Fill.tsx
- src/list/index.tsx
- src/list/tests/List.spec.tsx
If would be nice if the list could offer a mode that would fill the available space (height) with as many items that fit, instead of having to provide a number of items to render. The is issue is, that the list itself does the list item height calculation so as a user we'd have to duplicate that to calculated how many items could be visible in the space.
The other option would be to pass a "height" property that gives the list the height and then uses that to determine how many items should be in view.
> Offer option to fill the available height with items when using the list

- src/select/index.tsx
- src/select/tests/Select.spec.tsx
**Type:** bug
`Select` widget was not validating when there was an initial value set. Pending unit test
Resolves #1653
> Trigger onValidate when inital value is set on Select widget

- src/theme/dojo/card.m.css
- src/theme/material/card.m.css
Makes card widget default to full width. The card content section will expand to fill any empty space so that the action buttons remain on the bottom.
Resolves #1693
Screenshots with height and width set on parent:
> make card expand to parent height and width

- src/chip-typeahead/index.tsx
- src/chip-typeahead/tests/unit/ChipTypeahead.spec.tsx
- src/date-input/index.tsx
- src/examples/src/config.tsx
- src/examples/src/widgets/password-input/Disabled.tsx
- src/theme/default/chip-typeahead.m.css
- src/theme/default/chip-typeahead.m.css.d.ts
- src/theme/material/chip-typeahead.m.css
- src/theme/material/chip-typeahead.m.css.d.ts
- src/theme/material/chip.m.css
- src/theme/material/date-input.m.css
- src/theme/material/password-input.m.css
- src/theme/material/radio.m.css
- src/theme/material/select.m.css
- src/theme/material/select.m.css.d.ts
- src/theme/material/text-input.m.css
- src/theme/material/time-picker.m.css
Fixes various material theme issues where widgets are disabled including:
- typeahead
- chip typeahead
- date input
- time input
- radio
- chip
- password input
Resolves #1696
> [1696] - disabled state material theme issues

- src/theme/dojo/outlined-button.m.css
**Type:** bug
This pull request fixes focus styling and pressed state styling for the `OutlinedButton` using the Dojo theme.
Resolves #1682
> fix: outline button dojo theme

- src/theme/default/card.m.css
- src/theme/dojo/card.m.css
- src/theme/material/card.m.css
**Type:** bug
To support content using height 100% the content wrapper needs to have height 100%.
> The content wrapper needs to be height 100%

- src/card/index.tsx
- src/card/tests/unit/Card.spec.tsx
- src/examples/src/config.tsx
- src/examples/src/widgets/card/CardCombined.tsx
- src/examples/src/widgets/card/ClickableCard.tsx
- src/theme/dojo/card.m.css
- src/theme/material/card.m.css
This pull request renames the `Card` prop `onAction` to `onContentClick`, since it more-accurately describes what the prop actually does.
Resolves #1648
> fix: rename CardProperties.onAction to onContentClick

- src/time-picker/index.tsx
**Type:** bug
This pull request fixes an issue when using the `TimePicker` in Safari wherein formatting was offsetting the chosen display value by the locale-specific timezone offset. This issue did not present itself in other browsers because `toLocaleTimeString` appears to respect the time that's passed to it in all browsers but Safari.
_Before:_
_After:_
Resolves #1717
> fix: time picker formatting

- src/select/index.tsx
- src/select/tests/Select.spec.tsx
**Type:** bug
- If no item can be queried from the resource with the given `value`:
- `Select` will no longer display `value`
- `Select` will style itself as it empty
- Returned query results will be checked against the given `value` to ensure it matches
Resolves #1612
> 1612 - Select rejects bad values

- src/date-input/date-utils.tsx
- src/date-input/index.tsx
- src/date-input/tests/unit/DateInput.spec.tsx
- src/date-input/tests/unit/date-utils.spec.tsx
- src/examples/src/config.tsx
- src/examples/src/widgets/date-input/CustomParser.tsx
**Type:** bug
Adds support for more date formats and the ability to pass a custom date parser. This resolves an issue with the date handling outside of a few select locales and adds support for several common date formats (as defined by `Intl.DateTimeFormat().format()`). For other locales or for more flexible date parsing (such as to support multiple formats at once), a custom date formatter/parser combo can be passed.
For locales where `Intl.DateTimeFormat().format()` produces something that is not supported, selecting a date from the calendar was resulting in an invalid date warning. This was because the Date value is formatted as a string using `DateTimeFormat` and later parsed. The fix was adding a check to the …
> support more date formats and custom date parsers

- src/theme/default/card.m.css
- src/theme/dojo/card.m.css
- src/theme/material/card.m.css
**Type:** bug
Looks like the card content needs 100% width and height as in order to take up all the available space. It works properly in chrome but not in safari/ios.
> The card content needs 100% sizing to work properly on safari

- src/examples/src/config.tsx
- src/examples/src/widgets/wizard/StepContent.tsx
- src/examples/src/widgets/wizard/StepRenderer.tsx
- src/wizard/index.tsx
- src/wizard/tests/unit/Wizard.spec.tsx
This pull request adds custom content support to `Wizard` step configuration.
Resolves #1611
> feat: wizard content configuration

- src/time-picker/index.tsx
- src/time-picker/tests/unit/TimePicker.spec.tsx
**Type:** bug
This pull request fixes an issue with `TimePicker` that prevented required instances from failing validation.
Resolves #1714
> fix: correctly validate required TimePicker

- src/theme/material/select.m.css
**Type:** bug
This pull request fixes `Select` placeholder `z-index` styling using the Material theme.
Resolves #1729
> fix: select placeholder z-index

- src/typeahead/index.tsx
- src/typeahead/tests/unit/Typeahead.spec.tsx
Allow typeahead selection on tab in addition to enter.
Resolves #1564
> 1564 - Allow typeahead selection on tab

- src/theme/material/label.m.css
**Type:** bug
Match label color behavior to material specs. Primary on `focus`, secondary on `blur`. Previously it was primary on `active` which resulted in the label staying the primary color once a value in the parent text input or select was set.
Resolves #1715
> 1715 - Change label color on focus instead of on active for material theme

- src/date-input/index.tsx
- src/date-input/tests/unit/DateInput.spec.tsx
- src/examples/src/widgets/date-input/Required.tsx
**Type:** bug
Pass date input's required flag down to child text input
Resolves #1734
> 1734 - Pass date input's required flag down to child text input

- src/theme/material/label.m.css.d.ts
- src/theme/material/list-item.m.css
**Type:** bug
Fix width of list item's primary span to expand to fill parent, so loading indicators appear correctly.
Resolves #1730
> 1730 - Fix width of list item's primary span to expand to fill parent

- src/checkbox-group/index.tsx
- src/context-menu/index.tsx
- src/email-input/index.tsx
- src/form/index.tsx
- src/radio-group/index.tsx
- src/rate/index.tsx
- src/speed-dial/index.tsx
- src/three-column-layout/index.tsx
- src/two-column-layout/index.tsx
**Type:** bug
Fixes a few missing or incorrect widget names across the library. Widget names are very useful as they are used by the test renderer to show diffs for failing tests.
> Fix missing or incorrect widget names

- src/checkbox-group/index.tsx
- src/checkbox-group/tests/CheckboxGroup.spec.tsx
- src/radio-group/index.tsx
- src/radio-group/tests/RadioGroup.spec.tsx
This pull request adds a top-level `disabled` prop to both `CheckboxGroup` and `RadioGroup` and updates tests accordingly.
Resolves #1698
Replaces #1711
> feat: add disabled prop to radio and checkbox groups

- src/examples/src/config.tsx
- src/examples/src/widgets/list/CustomTheme.m.css
- src/examples/src/widgets/list/CustomTheme.m.css.d.ts
- src/examples/src/widgets/list/CustomTheme.tsx
- src/theme/dojo/chip-typeahead.m.css.d.ts
- src/theme/dojo/list-item.m.css
- src/theme/dojo/variants/dark.m.css
- src/theme/dojo/variants/default.m.css
- src/theme/material/chip-typeahead.m.css.d.ts
- src/theme/material/list-item.m.css
- src/theme/material/list-item.m.css.d.ts
- src/theme/material/variants/dark.m.css
- src/theme/material/variants/default.m.css
This pull request updates the `ListItem` by adding background and color variables to applicable states (disabled, active, selected) so that it can be themed independently of other widgets.
Resolves #1726
> feat: easier list item theming

- src/stack/Spacer.tsx
- src/stack/index.tsx
- src/stack/tests/Stack.spec.tsx
**Type:** bug
`diffProperty` needs to actually do the diff on the `span` property to determine if the callback needs to be called. Otherwise the the callback is called every time and ends up with causing an infinite render loop.
> Bug: Check span value in diff property

- src/card/index.tsx
- src/card/tests/unit/Card.spec.tsx
- src/examples/src/widgets/card/Outlined.tsx
- src/examples/src/widgets/header-card/Outlined.tsx
`kind` is the property to used consistently across widgets to determine the type of widget, in this case the `outlined` and `elevated`  card types. This converts the existing `outlined` property to `kind`
> Convert outlined property to kind 

- src/stack/index.tsx
- src/stack/tests/Stack.spec.tsx
**Type:** bug
Add key to stack children wrappers
> Bug: Add key to stacks

- src/examples/src/widgets/text/OverrideFont.tsx
- src/theme/dojo/button.m.css
- src/theme/dojo/variants/dark.m.css
- src/theme/dojo/variants/default.m.css
- src/theme/material/button.m.css
- src/theme/material/variants/dark.m.css
- src/theme/material/variants/default.m.css
Add specific vars to customise button styling without needing to change the main CSS var
> Add Button CSS Variables
